# **NLP Data Collection**
notebook by Jan Eliel Bualoy\
*from [JNV Teaching Notebooks](https://github.com/JNV-Teaching/teaching)*

Instructions:
- Choose a topic from the Rappler website. Then, scrape at least five pages of data.
- Look for related videos on YouTube with numerous comments.

# Method 1: Web Scraping

## Exploring the method

Install necessary packages

In [ ]:
!pip install beautifulsoup4 requests

Requirement already satisfied: beautifulsoup4 in ./venv/lib/python3.10/site-packages (4.13.4)
Requirement already satisfied: requests in ./venv/lib/python3.10/site-packages (2.32.4)
Requirement already satisfied: soupsieve>1.2 in ./venv/lib/python3.10/site-packages (from beautifulsoup4) (2.7)
Requirement already satisfied: typing-extensions>=4.0.0 in ./venv/lib/python3.10/site-packages (from beautifulsoup4) (4.14.1)
Requirement already satisfied: charset_normalizer<4,>=2 in ./venv/lib/python3.10/site-packages (from requests) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in ./venv/lib/python3.10/site-packages (from requests) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in ./venv/lib/python3.10/site-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in ./venv/lib/python3.10/site-packages (from requests) (2025.8.3)

Next, we import the packages into the notebook.
1. `pandas`: for managing data through dataframes (https://pandas.pydata.org/docs/)
2. `requests`: for connecting to webpages (needs an "agent" to emulate a web browser) (https://requests.readthedocs.io/en/latest/)
3. `beautifulsoup`: for processing HTML data collected from webpages (https://www.crummy.com/software/BeautifulSoup/)

In [ ]:
# Import libraries
import numpy as np
import pandas as pd
import requests
from bs4 import BeautifulSoup
import time
import random

# Declare headers for the requests agent
headers = {
  'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36 Edg/127.0.0.0',
  'Accept-Language': 'en-US,en;q=0.9',
  'Accept-Encoding': 'gzip, deflate, br',
  'Connection': 'keep-alive'
}

Let's try extracting the content of the article from Rappler:

[Sara Duterte face book isang kaibigan](https://www.rappler.com/newsbreak/fact-check/sara-duterte-face-book-isang-kaibigan/)

In [ ]:
# Define article based on the link
link = 'https://www.rappler.com/newsbreak/fact-check/sara-duterte-face-book-isang-kaibigan/'

# Request using `request` library
r = requests.get(link, headers=headers)
r

Look at the webpage's content

In [ ]:
# Inspect the content
r.content

b'<!doctype html>\n<html lang="en-US" class="no-js">\n<head>\n\t<meta charset="UTF-8">\n\t<meta name="viewport" content="width=device-width, initial-scale=1">\n\t<script>(function(c){c.add(\'has-js\');c.remove(\'no-js\')})(document.documentElement.classList)</script>\n\t\t<script>\n\t\t(function() {\n\t\t\tconst userAgent = navigator.userAgent;\n\n\t\t\t// Check if user agent contains mobile app identifiers\n\t\t\tif (userAgent.includes("RapplerMobileAndroid") ||\n\t\t\t\tuserAgent.includes("RapplerMobileiOS")) {\n\t\t\t\tdocument.documentElement.classList.add("r6-app");\n\t\t\t\tdocument.body.classList.add("hide-site-header");\n\t\t\t}\n\t\t})();\n\t</script>\n\t\t<meta name=\'robots\' content=\'index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1\' />\n<script>window.dataLayer = window.dataLayer || []; window.dataLayer.push( {"type":"post","subtype":"post","context":{"is_front_page":false,"is_singular":true,"is_archive":false,"is_home":false,"is_search":false,"is_404":false,"is_post_type_archive":false,"is_tax":false,"is_article":true},"user":{"role":[]},"blog":{"url":"https:\\/\\/www.rappler.com","id":1},"network":{"url":"https:\\/\\/www.rappler.com","id":1},"post":{"ID":2759297,"slug":"sara-duterte-face-book-isang-kaibigan","published":"2024-08-22 12:11:07","modified":"2024-08-22 12:11:24","comments":0,"template":"","thumbnail":"https:\\/\\/www.rappler.com\\/tachyon\\/2024\\/08\\/fc-ls-1.jpg","category":["Fact Check","National News","Newsbreak","Philippine News"],"movement":["factsfirstph"],"title":"FACT CHECK: VP Sara Duterte\'s face is in her book \'Isang Kaibigan\'","topics":["Fact checks on public officials","Duterte Fact Checks","Sara Duterte"],"primary_topic":"Fact checks on public officials","primary_category":"Fact Check","authors":["Rappler.com"],"author_ID":"4999","author_slug":"rappler-com"}} );</script>\n\t\t<!-- Google Tag Manager -->\n\t\t<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({\'gtm.start\':\n\t\tnew Date().getTime(),event:\'gtm.js\'});var f=d.getElementsByTagName(s)[0],\n\t\tj=d.createElement(s),dl=l!=\'dataLayer\'?\'&l=\'+l:\'\';j.async=true;j.src=\n\t\t\'https://www.googletagmanager.com/gtm.js?id=\'+i+dl;f.parentNode.insertBefore(j,f);\n\t\t})(window,document,\'script\',\'dataLayer\',\'GTM-WRN3RQG\');</script>\n\t\t<!-- End Google Tag Manager -->\n\t\t\n\t<!-- This site is optimized with the Yoast SEO Premium plugin v23.8 (Yoast SEO v23.8) - https://yoast.com/wordpress/plugins/seo/ -->\n\t<title>FACT CHECK: VP Sara Duterte&#039;s face is in her book &#039;Isang Kaibigan&#039;</title>\n\t<meta name="description" content="Numerous sources have shown pages of the book, one of which contains Duterte\xe2\x80\x99s picture along with some information about her" />\n\t<link rel="canonical" href="https://www.rappler.com/newsbreak/fact-check/sara-duterte-face-book-isang-kaibigan/" />\n\t<meta property="og:locale" content="en_US" />\n\t<meta property="og:type" content="article" />\n\t<meta property="og:title" content="FACT CHECK: VP Sara Duterte&#039;s face is in her book &#039;Isang Kaibigan&#039;" />\n\t<meta property="og:description" content="Numerous sources have shown pages of the book, one of which contains Duterte\xe2\x80\x99s picture along with some information about her" />\n\t<meta property="og:url" content="https://www.rappler.com/newsbreak/fact-check/sara-duterte-face-book-isang-kaibigan/" />\n\t<meta property="og:site_name" content="RAPPLER" />\n\t<meta property="article:published_time" content="2024-08-22T12:11:07+00:00" />\n\t<meta property="article:modified_time" content="2024-08-22T12:11:24+00:00" />\n\t<meta property="og:image" content="https://www.rappler.com/tachyon/2024/08/fc-ls-1.jpg" />\n\t<meta property="og:image:width" content="1280" />\n\t<meta property="og:image:height" content="720" />\n\t<meta property="og:image:type" content="image/jpeg" />\n\t<meta name="author" content="Lorenz Pasion" />\n\t<meta name="twitter:card" content="summary_large_image" />\n\t<meta name="twitter:image" content="https://www.rappler.com/tachyon/2024/08/fc-ls-1.jpg" />\n\t<meta name="twitter:creator" content="@rapplerdotcom" />\n\t<meta name="twitter:site" content="@rapplerdotcom" />\n\t<script type="application/ld+json" class="yoast-schema-graph">{"@context":"https://schema.org","@graph":[{"@type":["Article","ClaimReview"],"@id":"https://www.rappler.com/newsbreak/fact-check/sara-duterte-face-book-isang-kaibigan/#article","isPartOf":{"@id":"https://www.rappler.com/newsbreak/fact-check/sara-duterte-face-book-isang-kaibigan/"},"author":{"@id":"https://www.rappler.com/#/schema/person/6df94b691cab65f6e7ddef42b95b182b"},"headline":"FACT CHECK: VP Sara Duterte&#8217;s face is in her book &#8216;Isang Kaibigan&#8217;","datePublished":"2024-08-22T12:11:07+00:00","dateModified":"2024-08-22T12:11:24+00:00","mainEntityOfPage":{"@id":"https://www.rappler.com/newsbreak/fact-check/sara-duterte-face-book-isang-kaibigan/"},"wordCount":561,"commentCount":0,"publisher":{"@id":"https://www.rappler.com/#organization"},"image":{"@id":"https://www.rappler.com/newsbreak/fact-check/sara-duterte-face-book-isang-kaibigan/#primaryimage"},"thumbnailUrl":"https://www.rappler.com/tachyon/2024/08/fc-ls-1.jpg","keywords":"Fact checks on public officials, Duterte Fact Checks, Sara Duterte, Fact Check, National News, Newsbreak, Philippine News","articleSection":"Fact checks on public officials, Duterte Fact Checks, Sara Duterte","inLanguage":"en-US","potentialAction":[{"@type":"CommentAction","name":"Comment","target":["https://www.rappler.com/newsbreak/fact-check/sara-duterte-face-book-isang-kaibigan/#respond"]}],"itemReviewed":{"@type":"CreativeWork","datePublished":"2024-08-22T12:11:07+00:00","dateModified":"2024-08-22T12:11:24+00:00","author":{"@type":"Person","name":" \xe1\x8e\xa5\xe2\x93\x83\xe1\x97\xaa\xf0\x9d\x92\xb6\xf0\x9d\x95\xaa \xf0\x9d\x90\x8c\xf0\x9d\x94\xa6\xe2\x93\x88\xf0\x9d\x93\xbc \xf0\x9d\x93\x9c"}},"claimReviewed":"The face of Vice President Sara Duterte is not in the children\xe2\x80\x99s book that she wrote titled Isang Kaibigan.","reviewRating":{"@type":"Rating","alternateName":"False"},"url":"https://www.rappler.com/newsbreak/fact-check/sara-duterte-face-book-isang-kaibigan/","locationCreated":"Philippines","hasPart":[],"copyrightYear":"2024","copyrightHolder":{"@id":"https://www.rappler.com/#organization"}},{"@type":"WebPage","@id":"https://www.rappler.com/newsbreak/fact-check/sara-duterte-face-book-isang-kaibigan/","url":"https://www.rappler.com/newsbreak/fact-check/sara-duterte-face-book-isang-kaibigan/","name":"FACT CHECK: VP Sara Duterte\'s face is in her book \'Isang Kaibigan\'","isPartOf":{"@id":"https://www.rappler.com/#website"},"primaryImageOfPage":{"@id":"https://www.rappler.com/newsbreak/fact-check/sara-duterte-face-book-isang-kaibigan/#primaryimage"},"image":{"@id":"https://www.rappler.com/newsbreak/fact-check/sara-duterte-face-book-isang-kaibigan/#primaryimage"},"thumbnailUrl":"https://www.rappler.com/tachyon/2024/08/fc-ls-1.jpg","datePublished":"2024-08-22T12:11:07+00:00","dateModified":"2024-08-22T12:11:24+00:00","description":"Numerous sources have shown pages of the book, one of which contains Duterte\xe2\x80\x99s picture along with some information about her","breadcrumb":{"@id":"https://www.rappler.com/newsbreak/fact-check/sara-duterte-face-book-isang-kaibigan/#breadcrumb"},"inLanguage":"en-US","potentialAction":[{"@type":"ReadAction","target":["https://www.rappler.com/newsbreak/fact-check/sara-duterte-face-book-isang-kaibigan/"]}]},{"@type":"ImageObject","inLanguage":"en-US","@id":"https://www.rappler.com/newsbreak/fact-check/sara-duterte-face-book-isang-kaibigan/#primaryimage","url":"https://www.rappler.com/tachyon/2024/08/fc-ls-1.jpg","contentUrl":"https://www.rappler.com/tachyon/2024/08/fc-ls-1.jpg","width":1280,"height":720,"caption":"File, Person, Computer"},{"@type":"BreadcrumbList","@id":"https://www.rappler.com/newsbreak/fact-check/sara-duterte-face-book-isang-kaibigan/#breadcrumb","itemListElement":[{"@type":"ListItem","position":1,"name":"Latest News","item":"https://www.rappler.com/latest/"},{"@type":"ListItem","position":2,"name":"FACT CHECK: VP Sara Duterte&#8217;s face is in her book &#8216;Isang Kaibigan&#8217;"}]},{"@type":"WebSite","@id":"https://www.rappler.com/#website","url":"https://www.rappler.com/","name":"RAPPLER","description":"RAPPLER | Philippine &amp; World News | Investigative Journalism | Data | Civic Engagement | Public Interest","publisher":{"@id":"https://www.rappler.com/#organization"},"potentialAction":[{"@type":"SearchAction","target":{"@type":"EntryPoint","urlTemplate":"https://www.rappler.com/?s={search_term_string}"},"query-input":{"@type":"PropertyValueSpecification","valueRequired":true,"valueName":"search_term_string"}}],"inLanguage":"en-US"},{"@type":"Organization","@id":"https://www.rappler.com/#organization","name":"Rappler","url":"https://www.rappler.com/","logo":{"@type":"ImageObject","inLanguage":"en-US","@id":"https://www.rappler.com/#/schema/logo/image/","url":"https://www.rappler.com/uploads/2023/01/Rappler-Logo.svg","contentUrl":"https://www.rappler.com/uploads/2023/01/Rappler-Logo.svg","width":240,"height":200,"caption":"Rappler"},"image":{"@id":"https://www.rappler.com/#/schema/logo/image/"},"sameAs":["https://x.com/rapplerdotcom"]},{"@type":"Person","@id":"https://www.rappler.com/#/schema/person/6df94b691cab65f6e7ddef42b95b182b","name":"Rappler.com","image":{"@type":"ImageObject","inLanguage":"en-US","@id":"https://www.rappler.com/https://www.rappler.com/#/schema/person/6df94b691cab65f6e7ddef42b95b182b-logo","url":"https://secure.gravatar.com/avatar/?s=96&d=mm&r=g","contentUrl":"https://secure.gravatar.com/avatar/?s=96&d=mm&r=g","caption":"Rappler.com"},"url":""}]}</script>\n\t<!-- / Yoast SEO Premium plugin. -->\n\n\n<link rel="alternate" type="application/rss+xml" title="RAPPLER &raquo; Feed" href="https://www.rappler.com/feed/" />\n<link rel="alternate" type="application/rss+xml" title="RAPPLER &raquo; Comments Feed" href="https://www.rappler.com/comments/feed/" />\n<link rel="alternate" type="application/rss+xml" title="RAPPLER &raquo; FACT CHECK: VP Sara Duterte&#8217;s face is in her book &#8216;Isang Kaibigan&#8217; Comments Feed" href="https://www.rappler.com/newsbreak/fact-check/sara-duterte-face-book-isang-kaibigan/feed/" />\n<link rel="preload" href="https://www.rappler.com/content/themes/rappler/build/1cdec6e278f2e85e40f08af1112576f3.woff2" as="font" type="font/woff2" crossorigin />\n<link rel="preload" href="https://www.rappler.com/content/themes/rappler/build/6bbaad76a4547e68e0111da3ce1c929f.woff2" as="font" type="font/woff2" crossorigin />\n<link rel="preload" href="https://www.rappler.com/content/themes/rappler/build/8a64d0d4cd2b8d0ee70b9f60ecfbe8f8.woff2" as="font" type="font/woff2" crossorigin />\n<link rel="preload" href="https://www.rappler.com/content/themes/rappler/build/f55a0177f65edc649d6e45ba6a5a173f.woff2" as="font" type="font/woff2" crossorigin />\n<link rel="preload" href="https://www.rappler.com/wp-includes/css/dist/block-library/style.min.css?ver=6.6.2" as="style" />\n<link rel="preload" href="https://www.rappler.com/content/themes/rappler/build/rappler-theme-style.2d8f990814988b525d2e.css" as="style" />\n<link rel="preload" href="https://www.rappler.com/content/mu-plugins/rappler-blocks/build/rappler-blocks-frontend.d2edfed216c0e3671c75.css" as="style" />\n<link rel=\'stylesheet\' id=\'datatables-css-css\' href=\'https://cdn.datatables.net/v/dt/dt-2.1.7/fc-5.0.1/r-3.0.3/sc-2.4.3/datatables.min.css?ver=6.6.2\' media=\'all\' />\n<link rel=\'stylesheet\' id=\'wp-block-library-css\' href=\'https://www.rappler.com/wp-includes/css/dist/block-library/style.min.css?ver=6.6.2\' media=\'all\' />\n<style id=\'classic-theme-styles-inline-css\'>\n/*! This file is auto-generated */\n.wp-block-button__link{color:#fff;background-color:#32373c;border-radius:9999px;box-shadow:none;text-decoration:none;padding:calc(.667em + 2px) calc(1.333em + 2px);font-size:1.125em}.wp-block-file__button{background:#32373c;color:#fff;text-decoration:none}\n</style>\n<style id=\'global-styles-inline-css\'>\n:root{--wp--preset--aspect-ratio--square: 1;--wp--preset--aspect-ratio--4-3: 4/3;--wp--preset--aspect-ratio--3-4: 3/4;--wp--preset--aspect-ratio--3-2: 3/2;--wp--preset--aspect-ratio--2-3: 2/3;--wp--preset--aspect-ratio--16-9: 16/9;--wp--preset--aspect-ratio--9-16: 9/16;--wp--preset--color--black: #000000;--wp--preset--color--cyan-bluish-gray: #abb8c3;--wp--preset--color--white: #ffffff;--wp--preset--color--pale-pink: #f78da7;--wp--preset--color--vivid-red: #cf2e2e;--wp--preset--color--luminous-vivid-orange: #ff6900;--wp--preset--color--luminous-vivid-amber: #fcb900;--wp--preset--color--light-green-cyan: #7bdcb5;--wp--preset--color--vivid-green-cyan: #00d084;--wp--preset--color--pale-cyan-blue: #8ed1fc;--wp--preset--color--vivid-cyan-blue: #0693e3;--wp--preset--color--vivid-purple: #9b51e0;--wp--preset--color--navy: #172038;--wp--preset--color--orange-courage: #f04f3c;--wp--preset--color--ghost-white: #f5f6ff;--wp--preset--color--mint: #c7e4da;--wp--preset--color--vanilla: #fff;--wp--preset--color--move: #50558b;--wp--preset--gradient--vivid-cyan-blue-to-vivid-purple: linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%);--wp--preset--gradient--light-green-cyan-to-vivid-green-cyan: linear-gradient(135deg,rgb(122,220,180) 0%,rgb(0,208,130) 100%);--wp--preset--gradient--luminous-vivid-amber-to-luminous-vivid-orange: linear-gradient(135deg,rgba(252,185,0,1) 0%,rgba(255,105,0,1) 100%);--wp--preset--gradient--luminous-vivid-orange-to-vivid-red: linear-gradient(135deg,rgba(255,105,0,1) 0%,rgb(207,46,46) 100%);--wp--preset--gradient--very-light-gray-to-cyan-bluish-gray: linear-gradient(135deg,rgb(238,238,238) 0%,rgb(169,184,195) 100%);--wp--preset--gradient--cool-to-warm-spectrum: linear-gradient(135deg,rgb(74,234,220) 0%,rgb(151,120,209) 20%,rgb(207,42,186) 40%,rgb(238,44,130) 60%,rgb(251,105,98) 80%,rgb(254,248,76) 100%);--wp--preset--gradient--blush-light-purple: linear-gradient(135deg,rgb(255,206,236) 0%,rgb(152,150,240) 100%);--wp--preset--gradient--blush-bordeaux: linear-gradient(135deg,rgb(254,205,165) 0%,rgb(254,45,45) 50%,rgb(107,0,62) 100%);--wp--preset--gradient--luminous-dusk: linear-gradient(135deg,rgb(255,203,112) 0%,rgb(199,81,192) 50%,rgb(65,88,208) 100%);--wp--preset--gradient--pale-ocean: linear-gradient(135deg,rgb(255,245,203) 0%,rgb(182,227,212) 50%,rgb(51,167,181) 100%);--wp--preset--gradient--electric-grass: linear-gradient(135deg,rgb(202,248,128) 0%,rgb(113,206,126) 100%);--wp--preset--gradient--midnight: linear-gradient(135deg,rgb(2,3,129) 0%,rgb(40,116,252) 100%);--wp--preset--font-size--small: 13px;--wp--preset--font-size--medium: 20px;--wp--preset--font-size--large: 36px;--wp--preset--font-size--x-large: 42px;--wp--preset--spacing--20: 0.44rem;--wp--preset--spacing--30: 0.67rem;--wp--preset--spacing--40: 1rem;--wp--preset--spacing--50: 1.5rem;--wp--preset--spacing--60: 2.25rem;--wp--preset--spacing--70: 3.38rem;--wp--preset--spacing--80: 5.06rem;--wp--preset--shadow--natural: 6px 6px 9px rgba(0, 0, 0, 0.2);--wp--preset--shadow--deep: 12px 12px 50px rgba(0, 0, 0, 0.4);--wp--preset--shadow--sharp: 6px 6px 0px rgba(0, 0, 0, 0.2);--wp--preset--shadow--outlined: 6px 6px 0px -3px rgba(255, 255, 255, 1), 6px 6px rgba(0, 0, 0, 1);--wp--preset--shadow--crisp: 6px 6px 0px rgba(0, 0, 0, 1);}:where(.is-layout-flex){gap: 0.5em;}:where(.is-layout-grid){gap: 0.5em;}body .is-layout-flex{display: flex;}.is-layout-flex{flex-wrap: wrap;align-items: center;}.is-layout-flex > :is(*, div){margin: 0;}body .is-layout-grid{display: grid;}.is-layout-grid > :is(*, div){margin: 0;}:where(.wp-block-columns.is-layout-flex){gap: 2em;}:where(.wp-block-columns.is-layout-grid){gap: 2em;}:where(.wp-block-post-template.is-layout-flex){gap: 1.25em;}:where(.wp-block-post-template.is-layout-grid){gap: 1.25em;}.has-black-color{color: var(--wp--preset--color--black) !important;}.has-cyan-bluish-gray-color{color: var(--wp--preset--color--cyan-bluish-gray) !important;}.has-white-color{color: var(--wp--preset--color--white) !important;}.has-pale-pink-color{color: var(--wp--preset--color--pale-pink) !important;}.has-vivid-red-color{color: var(--wp--preset--color--vivid-red) !important;}.has-luminous-vivid-orange-color{color: var(--wp--preset--color--luminous-vivid-orange) !important;}.has-luminous-vivid-amber-color{color: var(--wp--preset--color--luminous-vivid-amber) !important;}.has-light-green-cyan-color{color: var(--wp--preset--color--light-green-cyan) !important;}.has-vivid-green-cyan-color{color: var(--wp--preset--color--vivid-green-cyan) !important;}.has-pale-cyan-blue-color{color: var(--wp--preset--color--pale-cyan-blue) !important;}.has-vivid-cyan-blue-color{color: var(--wp--preset--color--vivid-cyan-blue) !important;}.has-vivid-purple-color{color: var(--wp--preset--color--vivid-purple) !important;}.has-black-background-color{background-color: var(--wp--preset--color--black) !important;}.has-cyan-bluish-gray-background-color{background-color: var(--wp--preset--color--cyan-bluish-gray) !important;}.has-white-background-color{background-color: var(--wp--preset--color--white) !important;}.has-pale-pink-background-color{background-color: var(--wp--preset--color--pale-pink) !important;}.has-vivid-red-background-color{background-color: var(--wp--preset--color--vivid-red) !important;}.has-luminous-vivid-orange-background-color{background-color: var(--wp--preset--color--luminous-vivid-orange) !important;}.has-luminous-vivid-amber-background-color{background-color: var(--wp--preset--color--luminous-vivid-amber) !important;}.has-light-green-cyan-background-color{background-color: var(--wp--preset--color--light-green-cyan) !important;}.has-vivid-green-cyan-background-color{background-color: var(--wp--preset--color--vivid-green-cyan) !important;}.has-pale-cyan-blue-background-color{background-color: var(--wp--preset--color--pale-cyan-blue) !important;}.has-vivid-cyan-blue-background-color{background-color: var(--wp--preset--color--vivid-cyan-blue) !important;}.has-vivid-purple-background-color{background-color: var(--wp--preset--color--vivid-purple) !important;}.has-black-border-color{border-color: var(--wp--preset--color--black) !important;}.has-cyan-bluish-gray-border-color{border-color: var(--wp--preset--color--cyan-bluish-gray) !important;}.has-white-border-color{border-color: var(--wp--preset--color--white) !important;}.has-pale-pink-border-color{border-color: var(--wp--preset--color--pale-pink) !important;}.has-vivid-red-border-color{border-color: var(--wp--preset--color--vivid-red) !important;}.has-luminous-vivid-orange-border-color{border-color: var(--wp--preset--color--luminous-vivid-orange) !important;}.has-luminous-vivid-amber-border-color{border-color: var(--wp--preset--color--luminous-vivid-amber) !important;}.has-light-green-cyan-border-color{border-color: var(--wp--preset--color--light-green-cyan) !important;}.has-vivid-green-cyan-border-color{border-color: var(--wp--preset--color--vivid-green-cyan) !important;}.has-pale-cyan-blue-border-color{border-color: var(--wp--preset--color--pale-cyan-blue) !important;}.has-vivid-cyan-blue-border-color{border-color: var(--wp--preset--color--vivid-cyan-blue) !important;}.has-vivid-purple-border-color{border-color: var(--wp--preset--color--vivid-purple) !important;}.has-vivid-cyan-blue-to-vivid-purple-gradient-background{background: var(--wp--preset--gradient--vivid-cyan-blue-to-vivid-purple) !important;}.has-light-green-cyan-to-vivid-green-cyan-gradient-background{background: var(--wp--preset--gradient--light-green-cyan-to-vivid-green-cyan) !important;}.has-luminous-vivid-amber-to-luminous-vivid-orange-gradient-background{background: var(--wp--preset--gradient--luminous-vivid-amber-to-luminous-vivid-orange) !important;}.has-luminous-vivid-orange-to-vivid-red-gradient-background{background: var(--wp--preset--gradient--luminous-vivid-orange-to-vivid-red) !impor

Use `BeautifulSoup` to parse the webpage's HTML source code.

In [ ]:
# Use BeautifulSoup to parse the HTML page
soup = BeautifulSoup(r.content, 'html.parser')
soup

<!DOCTYPE html>

<html class="no-js" lang="en-US">
<head>
<meta charset="utf-8"/>
<meta content="width=device-width, initial-scale=1" name="viewport"/>
<script>(function(c){c.add('has-js');c.remove('no-js')})(document.documentElement.classList)</script>
<script>
		(function() {
			const userAgent = navigator.userAgent;

			// Check if user agent contains mobile app identifiers
			if (userAgent.includes("RapplerMobileAndroid") ||
				userAgent.includes("RapplerMobileiOS")) {
				document.documentElement.classList.add("r6-app");
				document.body.classList.add("hide-site-header");
			}
		})();
	</script>
<meta content="index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1" name="robots">
<script>window.dataLayer = window.dataLayer || []; window.dataLayer.push( {"type":"post","subtype":"post","context":{"is_front_page":false,"is_singular":true,"is_archive":false,"is_home":false,"is_search":false,"is_404":false,"is_post_type_archive":false,"is_tax":false,"is_article":true},"user":{"role":[]},"blog":{"url":"https:\/\/www.rappler.com","id":1},"network":{"url":"https:\/\/www.rappler.com","id":1},"post":{"ID":2759297,"slug":"sara-duterte-face-book-isang-kaibigan","published":"2024-08-22 12:11:07","modified":"2024-08-22 12:11:24","comments":0,"template":"","thumbnail":"https:\/\/www.rappler.com\/tachyon\/2024\/08\/fc-ls-1.jpg","category":["Fact Check","National News","Newsbreak","Philippine News"],"movement":["factsfirstph"],"title":"FACT CHECK: VP Sara Duterte's face is in her book 'Isang Kaibigan'","topics":["Fact checks on public officials","Duterte Fact Checks","Sara Duterte"],"primary_topic":"Fact checks on public officials","primary_category":"Fact Check","authors":["Rappler.com"],"author_ID":"4999","author_slug":"rappler-com"}} );</script>
<!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
		new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
		j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
		'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
		})(window,document,'script','dataLayer','GTM-WRN3RQG');</script>
<!-- End Google Tag Manager -->
<!-- This site is optimized with the Yoast SEO Premium plugin v23.8 (Yoast SEO v23.8) - https://yoast.com/wordpress/plugins/seo/ -->
<title>FACT CHECK: VP Sara Duterte's face is in her book 'Isang Kaibigan'</title>
<meta content="Numerous sources have shown pages of the book, one of which contains Duterte’s picture along with some information about her" name="description">
<link href="https://www.rappler.com/newsbreak/fact-check/sara-duterte-face-book-isang-kaibigan/" rel="canonical"/>
<meta content="en_US" property="og:locale"/>
<meta content="article" property="og:type"/>
<meta content="FACT CHECK: VP Sara Duterte's face is in her book 'Isang Kaibigan'" property="og:title"/>
<meta content="Numerous sources have shown pages of the book, one of which contains Duterte’s picture along with some information about her" property="og:description"/>
<meta content="https://www.rappler.com/newsbreak/fact-check/sara-duterte-face-book-isang-kaibigan/" property="og:url"/>
<meta content="RAPPLER" property="og:site_name"/>
<meta content="2024-08-22T12:11:07+00:00" property="article:published_time"/>
<meta content="2024-08-22T12:11:24+00:00" property="article:modified_time"/>
<meta content="https://www.rappler.com/tachyon/2024/08/fc-ls-1.jpg" property="og:image"/>
<meta content="1280" property="og:image:width"/>
<meta content="720" property="og:image:height"/>
<meta content="image/jpeg" property="og:image:type"/>
<meta content="Lorenz Pasion" name="author"/>
<meta content="summary_large_image" name="twitter:card"/>
<meta content="https://www.rappler.com/tachyon/2024/08/fc-ls-1.jpg" name="twitter:image"/>
<meta content="@rapplerdotcom" name="twitter:creator"/>
<meta content="@rapplerdotcom" name="twitter:site"/>
<script class="yoast-schema-graph" type="application/ld+json">{"@context":"https://schema.org","@graph":[{"@type":["Article","ClaimReview"],"@id":"https://www.rappler.com/newsbreak/fact-check/sara-duterte-face-book-isang-kaibigan/#article","isPartOf":{"@id":"https://www.rappler.com/newsbreak/fact-check/sara-duterte-face-book-isang-kaibigan/"},"author":{"@id":"https://www.rappler.com/#/schema/person/6df94b691cab65f6e7ddef42b95b182b"},"headline":"FACT CHECK: VP Sara Duterte&#8217;s face is in her book &#8216;Isang Kaibigan&#8217;","datePublished":"2024-08-22T12:11:07+00:00","dateModified":"2024-08-22T12:11:24+00:00","mainEntityOfPage":{"@id":"https://www.rappler.com/newsbreak/fact-check/sara-duterte-face-book-isang-kaibigan/"},"wordCount":561,"commentCount":0,"publisher":{"@id":"https://www.rappler.com/#organization"},"image":{"@id":"https://www.rappler.com/newsbreak/fact-check/sara-duterte-face-book-isang-kaibigan/#primaryimage"},"thumbnailUrl":"https://www.rappler.com/tachyon/2024/08/fc-ls-1.jpg","keywords":"Fact checks on public officials, Duterte Fact Checks, Sara Duterte, Fact Check, National News, Newsbreak, Philippine News","articleSection":"Fact checks on public officials, Duterte Fact Checks, Sara Duterte","inLanguage":"en-US","potentialAction":[{"@type":"CommentAction","name":"Comment","target":["https://www.rappler.com/newsbreak/fact-check/sara-duterte-face-book-isang-kaibigan/#respond"]}],"itemReviewed":{"@type":"CreativeWork","datePublished":"2024-08-22T12:11:07+00:00","dateModified":"2024-08-22T12:11:24+00:00","author":{"@type":"Person","name":" ᎥⓃᗪ𝒶𝕪 𝐌𝔦Ⓢ𝓼 𝓜"}},"claimReviewed":"The face of Vice President Sara Duterte is not in the children’s book that she wrote titled Isang Kaibigan.","reviewRating":{"@type":"Rating","alternateName":"False"},"url":"https://www.rappler.com/newsbreak/fact-check/sara-duterte-face-book-isang-kaibigan/","locationCreated":"Philippines","hasPart":[],"copyrightYear":"2024","copyrightHolder":{"@id":"https://www.rappler.com/#organization"}},{"@type":"WebPage","@id":"https://www.rappler.com/newsbreak/fact-check/sara-duterte-face-book-isang-kaibigan/","url":"https://www.rappler.com/newsbreak/fact-check/sara-duterte-face-book-isang-kaibigan/","name":"FACT CHECK: VP Sara Duterte's face is in her book 'Isang Kaibigan'","isPartOf":{"@id":"https://www.rappler.com/#website"},"primaryImageOfPage":{"@id":"https://www.rappler.com/newsbreak/fact-check/sara-duterte-face-book-isang-kaibigan/#primaryimage"},"image":{"@id":"https://www.rappler.com/newsbreak/fact-check/sara-duterte-face-book-isang-kaibigan/#primaryimage"},"thumbnailUrl":"https://www.rappler.com/tachyon/2024/08/fc-ls-1.jpg","datePublished":"2024-08-22T12:11:07+00:00","dateModified":"2024-08-22T12:11:24+00:00","description":"Numerous sources have shown pages of the book, one of which contains Duterte’s picture along with some information about her","breadcrumb":{"@id":"https://www.rappler.com/newsbreak/fact-check/sara-duterte-face-book-isang-kaibigan/#breadcrumb"},"inLanguage":"en-US","potentialAction":[{"@type":"ReadAction","target":["https://www.rappler.com/newsbreak/fact-check/sara-duterte-face-book-isang-kaibigan/"]}]},{"@type":"ImageObject","inLanguage":"en-US","@id":"https://www.rappler.com/newsbreak/fact-check/sara-duterte-face-book-isang-kaibigan/#primaryimage","url":"https://www.rappler.com/tachyon/2024/08/fc-ls-1.jpg","contentUrl":"https://www.rappler.com/tachyon/2024/08/fc-ls-1.jpg","width":1280,"height":720,"caption":"File, Person, Computer"},{"@type":"BreadcrumbList","@id":"https://www.rappler.com/newsbreak/fact-check/sara-duterte-face-book-isang-kaibigan/#breadcrumb","itemListElement":[{"@type":"ListItem","position":1,"name":"Latest News","item":"https://www.rappler.com/latest/"},{"@type":"ListItem","position":2,"name":"FACT CHECK: VP Sara Duterte&#8217;s face is in her book &#8216;Isang Kaibigan&#8217;"}]},{"@type":"WebSite","@id":"https://www.rappler.com/#website","url":"https://www.rappler.com/","name":"RAPPLER","description":"RAPPLER | Philippine &amp; World News | Investigative Journalism | Data | Civic Engagement | Public Interest","publisher":{"@id":"https://www.rappler.com/#organization"},"potentialAction":[{"@type":"SearchAction","target":{"@type":"EntryPoint","urlTemplate":"https://www.rappler.com/?s={search_term_string}"},"query-input":{"@type":"PropertyValueSpecification","valueRequired":true,"valueName":"search_term_string"}}],"inLanguage":"en-US"},{"@type":"Organization","@id":"https://www.rappler.com/#organization","name":"Rappler","url":"https://www.rappler.com/","logo":{"@type":"ImageObject","inLanguage":"en-US","@id":"https://www.rappler.com/#/schema/logo/image/","url":"https://www.rappler.com/uploads/2023/01/Rappler-Logo.svg","contentUrl":"https://www.rappler.com/uploads/2023/01/Rappler-Logo.svg","width":240,"height":200,"caption":"Rappler"},"image":{"@id":"https://www.rappler.com/#/schema/logo/image/"},"sameAs":["https://x.com/rapplerdotcom"]},{"@type":"Person","@id":"https://www.rappler.com/#/schema/person/6df94b691cab65f6e7ddef42b95b182b","name":"Rappler.com","image":{"@type":"ImageObject","inLanguage":"en-US","@id":"https://www.rappler.com/https://www.rappler.com/#/schema/person/6df94b691cab65f6e7ddef42b95b182b-logo","url":"https://secure.gravatar.com/avatar/?s=96&d=mm&r=g","contentUrl":"https://secure.gravatar.com/avatar/?s=96&d=mm&r=g","caption":"Rappler.com"},"url":""}]}</script>
<!-- / Yoast SEO Premium plugin. -->
<link href="https://www.rappler.com/feed/" rel="alternate" title="RAPPLER » Feed" type="application/rss+xml"/>
<link href="https://www.rappler.com/comments/feed/" rel="alternate" title="RAPPLER » Comments Feed" type="application/rss+xml"/>
<link href="https://www.rappler.com/newsbreak/fact-check/sara-duterte-face-book-isang-kaibigan/feed/" rel="alternate" title="RAPPLER » FACT CHECK: VP Sara Duterte’s face is in her book ‘Isang Kaibigan’ Comments Feed" type="application/rss+xml"/>
<link as="font" crossorigin="" href="https://www.rappler.com/content/themes/rappler/build/1cdec6e278f2e85e40f08af1112576f3.woff2" rel="preload" type="font/woff2"/>
<link as="font" crossorigin="" href="https://www.rappler.com/content/themes/rappler/build/6bbaad76a4547e68e0111da3ce1c929f.woff2" rel="preload" type="font/woff2"/>
<link as="font" crossorigin="" href="https://www.rappler.com/content/themes/rappler/build/8a64d0d4cd2b8d0ee70b9f60ecfbe8f8.woff2" rel="preload" type="font/woff2"/>
<link as="font" crossorigin="" href="https://www.rappler.com/content/themes/rappler/build/f55a0177f65edc649d6e45ba6a5a173f.woff2" rel="preload" type="font/woff2"/>
<link as="style" href="https://www.rappler.com/wp-includes/css/dist/block-library/style.min.css?ver=6.6.2" rel="preload"/>
<link as="style" href="https://www.rappler.com/content/themes/rappler/build/rappler-theme-style.2d8f990814988b525d2e.css" rel="preload"/>
<link as="style" href="https://www.rappler.com/content/mu-plugins/rappler-blocks/build/rappler-blocks-frontend.d2edfed216c0e3671c75.css" rel="preload"/>
<link href="https://cdn.datatables.net/v/dt/dt-2.1.7/fc-5.0.1/r-3.0.3/sc-2.4.3/datatables.min.css?ver=6.6.2" id="datatables-css-css" media="all" rel="stylesheet"/>
<link href="https://www.rappler.com/wp-includes/css/dist/block-library/style.min.css?ver=6.6.2" id="wp-block-library-css" media="all" rel="stylesheet"/>
<style id="classic-theme-styles-inline-css">
/*! This file is auto-generated */
.wp-block-button__link{color:#fff;background-color:#32373c;border-radius:9999px;box-shadow:none;text-decoration:none;padding:calc(.667em + 2px) calc(1.333em + 2px);font-size:1.125em}.wp-block-file__button{background:#32373c;color:#fff;text-decoration:none}
</style>
<style id="global-styles-inline-css">

We'll extract the following information to create our corpus.
* article link
* article title
* date published
* article's text / body
* *optional*: tags, i.e., related topic

### Extract the webpage's title.

In [ ]:
soup.title  # with HTML tags
soup.title.text  # text within the HTML tags
title = soup.title.text.strip()  # whitespaces are removed

### Extract the webpage's date published.

In [4]:
# Date published
date_published = soup.find(
  'time',  # HTML element tag
  {
      'class': 'published',
      'datetime': True
  }  # HTML attribute
)
# Actual text within the HTML element
date_published.text.strip()

# If you're after the HTML attribute, use the attribute name for the key
date_published = date_published['datetime']

AttributeError: 'NoneType' object has no attribute 'text'

### Extract the webpage's text

In [ ]:
# Extract article text
# element: div
# class: post-single__content entry-content
article_text = soup.find(
  'div',  # HTML element tag
  {
      'class': 'post-single__content entry-content'
  }  # HTML attribute
)
# Returns the HTML code for the article
article_text

# Get all paragraph (<p>) from the article_text
tagged_lines = article_text.find_all('p')  # Return list of paragraph elements

# Removes the HTML tags
text = ''
for line in tagged_lines:
  untagged_line = line.get_text()
  text += untagged_line + '\n'

# Returns the article text as 1 big string
print(text)

Claim: The face of Vice President Sara Duterte is not in the children’s book that she wrote titled, “Isang Kaibigan“.
Why we fact-checked this: The claim can be found in an August 21 post on social media platform X (formerly Twitter). The post says: “Yung libro na ni anino ni VPISD eh wala nga dyan” (The book that does not bear even a hint of a shadow of VPISD [Vice President Inday Sara Duterte] is not there).
The post also includes a video from the TikTok account “klc4.0” which — referring to Duterte’s book, Isang Kaibigan — says: “Yung libro ni Sara Duterte na walang mukha niya” (The book of Sara Duterte that does not carry her face).
As of writing, the post on X already has around 51 comments, 50 shares, 135 reactions, 7 bookmarks, and 23,800 video views. The source video on TikTok, meanwhile, has around 198,700 views, 3,690 reactions, 1,076 comments, 226 bookmarks, and 138 shares.
Both the X post and the TikTok video compare Sara Duterte and Senator Risa Hontiveros, pointing out the supposed absence of Duterte’s face in her book unlike Hontiveros whose face is supposedly on billboards and buses.
The facts: Vice President Sara Duterte’s book, “Isang Kaibigan” actually shows her face at the end of the book.
Numerous news reports have shown the page of the book that contains Duterte’s picture, along with some biographical details and the statement, “Siya ay isang tunay na kaibigan” (She is a true friend). Examples are news articles published on August 21 by Rappler, Philstar.com, and Inquirer.net.
What’s the issue: The controversy over the book arose during the August 20 budget hearing for the Office of the Vice President’s (OVP) proposed 2025 budget. Senator Hontiveros asked Duterte about the book for which the OVP allotted a P10-million budget for printing and distribution.
Duterte, however, replied, accusing Hontiveros of “politicizing the budget hearing.” This did not sit well with senator, who later on told Duterte: “Budget hearing po ito. Hindi po lahat about you. Pera po ito ng taong bayan.” (This is a budget hearing. Not everything is about you. This is about public funds.) (READ: Rappler Recap: Sara Duterte, Risa Hontiveros clash during Senate budget hearing)
Duterte’s book is about an owl (Kwago) with many friends. A storm damaged the owl’s home; with the others gone, one of the owl’s friends, a parrot (Loro), offered to help the owl recover from the storm’s effects. – Percival Bueser/ Rappler.com
Percival Bueser is a graduate of Rappler’s fact-checking mentorship program. This fact check was reviewed by a member of Rappler’s research team and a senior editor. Learn more about Rappler’s fact-checking mentorship program here.
Keep us aware of suspicious Facebook pages, groups, accounts, websites, articles, or photos in your network by contacting us at factcheck@rappler.com. You may also report dubious claims to #FactsFirstPH tipline by messaging Rappler on Facebook or Newsbreak via Twitter direct message. You may also report through our Viber fact check chatbot. Let us battle disinformation one Fact Check at a time.

### Extract topic tags

In [ ]:
# Retrieve tags (topics under related-topics-links)
tags_div = soup.find("div", {"class": "related-topics-links"})
tags = []
if tags_div:
    tags = [a.get_text(strip=True) for a in tags_div.find_all("a")]

print(tags)

['Duterte Fact Checks', 'Sara Duterte']

### Combine features into dataframe

In [ ]:
# Link
# Title
# Date Published
# Article's Text
rappler = pd.DataFrame(
    columns=['title', 'link', 'date_published', 'text', 'tags']
)
doc_details = [title, link, date_published, text, tags]
rappler.loc[len(rappler)] = doc_details
rappler

,title,link,date_published,text,tags
0,FACT CHECK: VP Sara Duterte's face is in her b...,https://www.rappler.com/newsbreak/fact-check/s...,2024-08-22T20:11:07+08:00,Claim: The face of Vice President Sara Duterte...,"[Duterte Fact Checks, Sara Duterte]"

### Export to Excel file

In [ ]:
file_name = 'rappler.xlsx'

rappler.to_excel(file_name)
print(f'File saved to {file_name}')

File saved to rappler.xlsx

## Function `extract_article_data`

In [1]:
# Import libraries
import numpy as np
import pandas as pd
import requests
from bs4 import BeautifulSoup
import time
import random

# Declare headers for the requests agent
headers = {
  'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36 Edg/127.0.0.0',
  'Accept-Language': 'en-US,en;q=0.9',
  'Accept-Encoding': 'gzip, deflate, br',
  'Connection': 'keep-alive'
}

In [5]:
# Extract data from article based on link
def extract_article_data(link):
  """
  Extracts data from an article based on the provided link.

  Parameters:
    link (str): The URL of the article.

  Returns:
    list: A list containing the extracted article details in the following order:
      - title (str): The title of the article.
      - date (str): The date the article was published.
      - link (str): The URL of the article.
      - text (str): The content of the article.
      - tags (list[str]): A list of tags/topics attached to the article.
  """
  # Make a GET request for the article URL
  r = requests.get(link, headers=headers)

  # Parse the HTML
  soup = BeautifulSoup(r.content, 'html.parser')

  # Retrieve doc title
  title = soup.title.text.strip()

  # IF NOT WITH RAPPLER ARTICLE, CHANGE THIS XOXO
  # Retrieve doc date
  date = soup.find("time", {"datetime": True})['datetime']

  # IF NOT WITH RAPPLER ARTICLE, CHANGE THIS XOXO
  # Retrieve article content
  text = ''
  tagged_lines = soup.find("div", {"class": "post-single__content entry-content"}).find_all('p')
  for line in tagged_lines:
    untagged_line = line.get_text()
    text += untagged_line + '\n'

  # Retrieve tags (topics under related-topics-links)
  tags_div = soup.find("div", {"class": "related-topics-links"})
  tags = []
  if tags_div:
      tags = [a.get_text(strip=True) for a in tags_div.find_all("a")]

  # Create list containing doc details
  # Append to dataset
  doc_details = [title, date, link, text, tags]
  return doc_details

In [ ]:
# Test the `extract_article_data` function
rappler.loc[len(rappler)] = extract_article_data(
  'https://www.rappler.com/philippines/hontiveros-seek-realignment-sara-duterte-book-fund-request-2025-budget/'
)
rappler

,title,link,date_published,text,tags
0,FACT CHECK: VP Sara Duterte's face is in her b...,https://www.rappler.com/newsbreak/fact-check/s...,2024-08-22T20:11:07+08:00,Claim: The face of Vice President Sara Duterte...,"[Duterte Fact Checks, Sara Duterte]"
1,Hontiveros to seek realignment of Sara Duterte...,2024-08-22T13:05:55+08:00,https://www.rappler.com/philippines/hontiveros...,"MANILA, Philippines – Senator Risa Hontiveros ...","[Philippine national budget 2025, Risa Hontive..."

## TOPIC Scraping
To extract multiple articles from a given [topic](https://www.rappler.com/topic-directory/), we can get the topic ID to paginate the Load More. This also includes PEOPLE, WORLD and other category of topics.

In [2]:
# Extract topic ID from a Rappler topic page
topic_url = "https://www.rappler.com/philippines/government/n47851081-dpwh/" # @param {type:"string"}

r = requests.get(topic_url, headers=headers)
soup = BeautifulSoup(r.text, "html.parser")

# Get the first element that has data-post-id
el = soup.find(attrs={"data-post-id": True})

if el:
    topic_id = int(el["data-post-id"])
    print("Topic ID:", topic_id)

Topic ID: 2649159

In [6]:
base_url = f"https://www.rappler.com/wp-json/rappler/v1/ontology-topics/{topic_id}/latest-news?page="

page = 1
page_limit = 50   # adjust as needed
corpus = pd.DataFrame(columns=['title', 'date_published', 'link', 'text', 'tags'])

while page <= page_limit:
    url = base_url + str(page)
    print(f"Fetching {url}")

    articles = requests.get(url, headers=headers).json()

    if not articles:
        print("No more articles found. Stopping.")
        break

    for a in articles:
        # skip if it's not an article object
        if not isinstance(a, dict) or not a.get("permalink"):
            continue

        try:
            row = extract_article_data(a["permalink"])
            if row:
                corpus.loc[len(corpus)] = row
        except Exception as e:
            print(f"Failed to extract {a.get('permalink')}: {e}")
            continue

    time.sleep(random.randint(1,3))
    page += 1

print("Done! Extracted", len(corpus), "articles")

Fetching https://www.rappler.com/wp-json/rappler/v1/ontology-topics/2649159/latest-news?page=1
Fetching https://www.rappler.com/wp-json/rappler/v1/ontology-topics/2649159/latest-news?page=2
Fetching https://www.rappler.com/wp-json/rappler/v1/ontology-topics/2649159/latest-news?page=3
Fetching https://www.rappler.com/wp-json/rappler/v1/ontology-topics/2649159/latest-news?page=4
Fetching https://www.rappler.com/wp-json/rappler/v1/ontology-topics/2649159/latest-news?page=5
Fetching https://www.rappler.com/wp-json/rappler/v1/ontology-topics/2649159/latest-news?page=6
Fetching https://www.rappler.com/wp-json/rappler/v1/ontology-topics/2649159/latest-news?page=7
Fetching https://www.rappler.com/wp-json/rappler/v1/ontology-topics/2649159/latest-news?page=8
Fetching https://www.rappler.com/wp-json/rappler/v1/ontology-topics/2649159/latest-news?page=9
Fetching https://www.rappler.com/wp-json/rappler/v1/ontology-topics/2649159/latest-news?page=10
Fetching https://www.rappler.com/wp-json/rappler/v1/ontology-topics/2649159/latest-news?page=11
Fetching https://www.rappler.com/wp-json/rappler/v1/ontology-topics/2649159/latest-news?page=12
Fetching https://www.rappler.com/wp-json/rappler/v1/ontology-topics/2649159/latest-news?page=13
Fetching https://www.rappler.com/wp-json/rappler/v1/ontology-topics/2649159/latest-news?page=14
Fetching https://www.rappler.com/wp-json/rappler/v1/ontology-topics/2649159/latest-news?page=15
Fetching https://www.rappler.com/wp-json/rappler/v1/ontology-topics/2649159/latest-news?page=16
Fetching https://www.rappler.com/wp-json/rappler/v1/ontology-topics/2649159/latest-news?page=17
Fetching https://www.rappler.com/wp-json/rappler/v1/ontology-topics/2649159/latest-news?page=18
Fetching https://www.rappler.com/wp-json/rappler/v1/ontology-topics/2649159/latest-news?page=19
Fetching https://www.rappler.com/wp-json/rappler/v1/ontology-topics/2649159/latest-news?page=20
Fetching https://www.rappler.com/wp-json/rappler/v1/ontology-topics/2649159/latest-news?page=21
Fetching https://www.rappler.com/wp-json/rappler/v1/ontology-topics/2649159/latest-news?page=22
Fetching https://www.rappler.com/wp-json/rappler/v1/ontology-topics/2649159/latest-news?page=23
Fetching https://www.rappler.com/wp-json/rappler/v1/ontology-topics/2649159/latest-news?page=24
Fetching https://www.rappler.com/wp-json/rappler/v1/ontology-topics/2649159/latest-news?page=25
Fetching https://www.rappler.com/wp-json/rappler/v1/ontology-topics/2649159/latest-news?page=26
Fetching https://www.rappler.com/wp-json/rappler/v1/ontology-topics/2649159/latest-news?page=27
Fetching https://www.rappler.com/wp-json/rappler/v1/ontology-topics/2649159/latest-news?page=28
Fetching https://www.rappler.com/wp-json/rappler/v1/ontology-topics/2649159/latest-news?page=29
Fetching https://www.rappler.com/wp-json/rappler/v1/ontology-topics/2649159/latest-news?page=30
Fetching https://www.rappler.com/wp-json/rappler/v1/ontology-topics/2649159/latest-news?page=31
Fetching https://www.rappler.com/wp-json/rappler/v1/ontology-topics/2649159/latest-news?page=32
Fetching https://www.rappler.com/wp-json/rappler/v1/ontology-topics/2649159/latest-news?page=33
Fetching https://www.rappler.com/wp-json/rappler/v1/ontology-topics/2649159/latest-news?page=34
Fetching https://www.rappler.com/wp-json/rappler/v1/ontology-topics/2649159/latest-news?page=35
Fetching https://www.rappler.com/wp-json/rappler/v1/ontology-topics/2649159/latest-news?page=36
Fetching https://www.rappler.com/wp-json/rappler/v1/ontology-topics/2649159/latest-news?page=37
Fetching https://www.rappler.com/wp-json/rappler/v1/ontology-topics/2649159/latest-news?page=38
Fetching https://www.rappler.com/wp-json/rappler/v1/ontology-topics/2649159/latest-news?page=39
Fetching https://www.rappler.com/wp-json/rappler/v1/ontology-topics/2649159/latest-news?page=40
Fetching https://www.rappler.com/wp-json/rappler/v1/ontology-topics/2649159/latest-news?page=41
Fetching https://www.rappler.com/wp-json/rappler/v1/ontology-topics/2649159/latest-news?page=42
Fetching https://www.rappler.com/wp-json/rappler/v1/ontology-topics/2649159/latest-news?page=43
Fetching https://www.rappler.com/wp-json/rappler/v1/ontology-topics/2649159/latest-news?page=44
Fetching https://www.rappler.com/wp-json/rappler/v1/ontology-topics/2649159/latest-news?page=45
Fetching https://www.rappler.com/wp-json/rappler/v1/ontology-topics/2649159/latest-news?page=46
Fetching https://www.rappler.com/wp-json/rappler/v1/ontology-topics/2649159/latest-news?page=47
Fetching https://www.rappler.com/wp-json/rappler/v1/ontology-topics/2649159/latest-news?page=48
Fetching https://www.rappler.com/wp-json/rappler/v1/ontology-topics/2649159/latest-news?page=49
Fetching https://www.rappler.com/wp-json/rappler/v1/ontology-topics/2649159/latest-news?page=50
Done! Extracted 246 articles

In [7]:
import openpyxl

file_name = 'rappler_corpus.xlsx'

corpus.to_excel(file_name)
print(f'File saved to {file_name}')

File saved to rappler_corpus.xlsx

In [8]:
corpus

,title,date_published,link,text,tags
0,"'Widespread destruction, tampering' of flood p...",2025-09-22T16:35:25+08:00,https://www.rappler.com/philippines/dpwh-flood...,"MANILA, Philippines – The Independent Commissi...","[corruption, Corruption in the Philippines, DP..."
1,Bojie Dy wants House infra comm probe into flo...,2025-09-22T13:04:13+08:00,https://www.rappler.com/philippines/bojie-dy-w...,"MANILA, Philippines – New Speaker Bojie Dy sai...","[Corruption in the Philippines, DPWH, Faustino..."
2,Ilonggos demand gov’t action on unfinished P80...,2025-09-22T11:27:53+08:00,https://www.rappler.com/philippines/visayas/il...,"ILOILO CITY, Philippines – Nearly three years ...","[Corruption in the Philippines, DPWH, Iloilo, ..."
3,Protesters defy rain at Trillion Peso March,2025-09-21T21:48:59+08:00,https://www.rappler.com/philippines/protesters...,"MANILA, Philippines – Protesters defied rain o...","[DPWH, flood control]"
4,Why these Claretian seminarians joined the Tri...,2025-09-21T21:11:27+08:00,https://www.rappler.com/philippines/why-claret...,"MANILA, Philippines – A group of Claretian sem...","[DPWH, flood control, protests in the Philippi..."
...,...,...,...,...,...
241,Ex-Central Visayas DPWH execs convicted in ove...,2020-10-01T22:23:41+08:00,https://www.rappler.com/philippines/ex-central...,The anti-graft court Sandiganbayan convicted T...,"[Cebu City, Central Visayas, DPWH, Sandiganbayan]"
242,Lawmakers question withheld P135-B DPWH funds,2020-09-22T19:14:09+08:00,https://www.rappler.com/business/lawmakers-que...,"Lawmakers on Tuesday, September 22, questioned...","[DPWH, Philippine national budget]"
243,"Preview of speakership showdown? Cayetano, Vel...",2020-09-18T11:16:41+08:00,https://www.rappler.com/philippines/cayetano-v...,Allies of Speaker Alan Peter Cayetano and riva...,"[Alan Peter Cayetano, Budget Watch, DPWH, Phil..."
244,Biggest hike yet only 5 execs present? House p...,2020-09-17T20:36:09+08:00,https://www.rappler.com/newsbreak/inside-track...,"Among government agencies, the Department of P...","[DPWH, House of Representatives, Philippine na..."
245,"Lacson hits P469 B in lump sums, rehashed item...",2020-09-09T17:55:26+08:00,https://www.rappler.com/philippines/lacson-hit...,"Senator Panfilo Lacson on Wednesday, September...","[DPWH, Philippine national budget, Senate of t..."

## SEARCH QUERY Scraping
To load the Google Search Query, we need to load the websites dynnamic content due to the Google Custom Search.\
For this, we can use [Selenium](https://www.selenium.dev/documentation/) to dynamically load all the contents of the website by using a webdriver.\
For this example the base url of the rappler search query can be paginated by modifying the gsc.page attribute.\
To find the link to the article, we can use the class "gs-title" which has an "href" attribute we are looking for.

In [ ]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.options import Options


# --- Setup Selenium ---
options = Options()
options.add_argument("--headless")  # run without opening a browser window
options.add_argument("--no-sandbox")
options.add_argument("--disable-dev-shm-usage")

driver = webdriver.Chrome(options=options)

# --- Search query ---
query = "china"
base_url = f"https://www.rappler.com/?q={query}#gsc.tab=0&gsc.q={query}&gsc.page="
page_limit = 3

corpus = pd.DataFrame(columns=['title', 'date_published', 'link', 'text', 'tags'])

for page in range(1, page_limit + 1):
    url = base_url + str(page)
    print(f"Fetching page {page}: {url}")
    driver.get(url)
    time.sleep(3)  # wait for JS to load results

    # Extract article links
    links = driver.find_elements(By.CSS_SELECTOR, "a.gs-title")
    article_links = [a.get_attribute("href") for a in links if a.get_attribute("href")]

    if not article_links:
        print("No articles found on this page. Stopping.")
        break

    # Loop through each article link
    for link in article_links:
        try:
            row = extract_article_data(link)
            if row:
                if row[2] not in corpus["link"].values:  # row[2] = link
                    corpus.loc[len(corpus)] = row
        except Exception as e:
            print(f"Failed to extract {link}: {e}")
            continue

driver.quit()

print("Done! Extracted", len(corpus), "articles")

Fetching page 1: https://www.rappler.com/?q=china#gsc.tab=0&gsc.q=china&gsc.page=1
Failed to extract https://www.rappler.com/world/asia-pacific/n81633472-china/: 'NoneType' object has no attribute 'find_all'
Failed to extract https://www.rappler.com/world/asia-pacific/n81633472-china/: 'NoneType' object has no attribute 'find_all'
Failed to extract https://www.rappler.com/topic/philippines-china-relations/: 'NoneType' object has no attribute 'find_all'
Failed to extract https://www.rappler.com/topic/philippines-china-relations/: 'NoneType' object has no attribute 'find_all'
Failed to extract https://www.rappler.com/topic/us-china-relations/: 'NoneType' object has no attribute 'find_all'
Failed to extract https://www.rappler.com/topic/us-china-relations/: 'NoneType' object has no attribute 'find_all'
Fetching page 2: https://www.rappler.com/?q=china#gsc.tab=0&gsc.q=china&gsc.page=2
Fetching page 3: https://www.rappler.com/?q=china#gsc.tab=0&gsc.q=china&gsc.page=3
Done! Extracted 57 articles

In [ ]:
import openpyxl

file_name = 'rappler_corpus_search.xlsx'

corpus.to_excel(file_name)
print(f'File saved to {file_name}')

File saved to rappler_corpus_search.xlsx

# Method 2: Using the YouTube API

## Create YouTube Data API v3 key

Before we can scrape data from YouTube, we need to get an API key. APIs, or Application Programming Interfaces, are ways in which two applications (e.g., Google Colaboratory and YouTube) can talk to each other. You can think of it as the language through which two apps can speak so they can send and receive information from each other.

Some apps (e.g., YouTube and Google services) require an API key, or a string of characters that authenticates a user to access the app through an API.

1.   To get your API key, head to https://console.cloud.google.com/cloud-resource-manager
2.   Click on Create Project, name the project "YouTube scraping," and press "CREATE"
3.   In your Google Developers Console dashboard, click the Navigation Menu (the three lines) at the upper left corner and select "APIs & Services"
4.   When prompted, select the "YouTube scraping" project
5.   You will be directed to the project's dashboard, where you are to click "Explore & Enable APIs"
6.   Search for and select "YouTube Data API v3"
7.   Enable the API and click "Create Credentials"
8.   Select "public data" when asked what kind of data you will access
9.   Find your API key at the "Credentials" tab on the left side of your dashboard (If it's not there, just click "Create Credentials" again and select "API key")

Now, we import the pertinent packages.

`build` creates a resource object that uses the API key to communicate with YouTube.

In [ ]:
import pandas as pd
from googleapiclient.discovery import build
from dotenv import load_dotenv
import os

load_dotenv()
api_key = os.getenv("YOUTUBE_API_KEY")

In [ ]:
api_key = os.getenv("YOUTUBE_API_KEY")
youtube = build('youtube', 'v3', developerKey=api_key)

Let's make it our goal to make a corpus based on YouTube comments about Alice Guo.
Let's start with this link: https://www.youtube.com/watch?v=yfoq-0gGTLM

To get comment thread results from YouTube, we execute the code below that uses the `commentThreads()` and `list` methods with two arguments:
*   `id`, which we get from the link above
*   `parts`, which we set as "snippet,replies" because these are the only parts of the comment results we are interested in

To learn more about how to use the YouTube API to get comment thread results, refer to https://developers.google.com/youtube/v3/docs/commentThreads/list

Now, let's try and look at the contents of the video_response object.

## Extract the YouTube comments

In [ ]:
video_id = '84-cHoF2-KM'
video_response = youtube.commentThreads().list(
  videoId=video_id, part='snippet,replies', maxResults=100,
  order='time'
).execute()
video_response

{'kind': 'youtube#commentThreadListResponse',
 'etag': 'S6QWRVPsfJUJO-Z7WY5SyKHcVQs',
 'nextPageToken': 'Z2V0X25ld2VzdF9maXJzdC0tQ2dnSWdBUVZGN2ZST0JJRkNLZ2dHQUFTQlFpSElCZ0FFZ1VJaVNBWUFCSUZDSWdnR0FBU0JRaWRJQmdCSWc0S0RBal9oZlhFQmhENDk2N1RBdw==',
 'pageInfo': {'totalResults': 100, 'resultsPerPage': 100},
 'items': [{'kind': 'youtube#commentThread',
   'etag': 'QZgq4aruyLz7UPM1McYN_mhMmik',
   'id': 'UgxjnwJEowNi2_gDy2t4AaABAg',
   'snippet': {'channelId': 'UCvRAX-ujvZ0eTMLGG2vki9w',
    'videoId': '84-cHoF2-KM',
    'topLevelComment': {'kind': 'youtube#comment',
     'etag': 'DIZA2o_z_tvNofuufcmczzjjAwQ',
     'id': 'UgxjnwJEowNi2_gDy2t4AaABAg',
     'snippet': {'channelId': 'UCvRAX-ujvZ0eTMLGG2vki9w',
      'videoId': '84-cHoF2-KM',
      'textDisplay': 'US ain&#39;t going to defend you when the real battle begins.  Filipino should stop trying acting tough. Filipino are just little Chihuahua.',
      'textOriginal': "US ain't going to defend you when the real battle begins.  Filipino should stop trying acting tough. Filipino are just little Chihuahua.",
      'authorDisplayName': '@kaibrunnenG',
      'authorProfileImageUrl': 'https://yt3.ggpht.com/ytc/AIdro_nO-aIjE2WmAUpCbCYfhnWNChhmI95UWMmIcofUeZE=s48-c-k-c0x00ffffff-no-rj',
      'authorChannelUrl': 'http://www.youtube.com/@kaibrunnenG',
      'authorChannelId': {'value': 'UCetE3OXkSjAmBfWmN5Y5khw'},
      'canRate': True,
      'viewerRating': 'none',
      'likeCount': 0,
      'publishedAt': '2025-08-23T01:58:32Z',
      'updatedAt': '2025-08-23T01:58:52Z'}},
    'canReply': True,
    'totalReplyCount': 0,
    'isPublic': True}},
  {'kind': 'youtube#commentThread',
   'etag': '_lu3fbY1-pvPhW_SdSSEoChpztY',
   'id': 'Ugz1q3NcOyPrB1f9B394AaABAg',
   'snippet': {'channelId': 'UCvRAX-ujvZ0eTMLGG2vki9w',
    'videoId': '84-cHoF2-KM',
    'topLevelComment': {'kind': 'youtube#comment',
     'etag': 'wLG8bHE4ujtTE8gmKJyktIKQmXA',
     'id': 'Ugz1q3NcOyPrB1f9B394AaABAg',
     'snippet': {'channelId': 'UCvRAX-ujvZ0eTMLGG2vki9w',
      'videoId': '84-cHoF2-KM',
      'textDisplay': 'Chinese ships should be easy to sink if built like their automobiles.',
      'textOriginal': 'Chinese ships should be easy to sink if built like their automobiles.',
      'authorDisplayName': '@GitchWarrior52',
      'authorProfileImageUrl': 'https://yt3.ggpht.com/ytc/AIdro_nWiuO90asWaDtdNfrxtDtEIUJoNaX45tc9_yoPGvwlbiR9=s48-c-k-c0x00ffffff-no-rj',
      'authorChannelUrl': 'http://www.youtube.com/@GitchWarrior52',
      'authorChannelId': {'value': 'UC3LQpH5wIcM_SaPdSl3YRkw'},
      'canRate': True,
      'viewerRating': 'none',
      'likeCount': 0,
      'publishedAt': '2025-08-20T20:31:17Z',
      'updatedAt': '2025-08-20T20:31:17Z'}},
    'canReply': True,
    'totalReplyCount': 0,
    'isPublic': True}},
  {'kind': 'youtube#commentThread',
   'etag': 'RT_lEesYY_ZsdDIbr2-QF2dXHew',
   'id': 'UgzwL2IScdwNm66XAnB4AaABAg',
   'snippet': {'channelId': 'UCvRAX-ujvZ0eTMLGG2vki9w',
    'videoId': '84-cHoF2-KM',
    'topLevelComment': {'kind': 'youtube#comment',
     'etag': 'hcYnlh8gBYu6Dmdevc1rzSzXCoo',
     'id': 'UgzwL2IScdwNm66XAnB4AaABAg',
     'snippet': {'channelId': 'UCvRAX-ujvZ0eTMLGG2vki9w',
      'videoId': '84-cHoF2-KM',
      'textDisplay': 'Erase china from world map',
      'textOriginal': 'Erase china from world map',
      'authorDisplayName': '@Sandy-q1p',
      'authorProfileImageUrl': 'https://yt3.ggpht.com/ytc/AIdro_nlK0XZCHPihWVQ4ZXtf5b8YpsaViKGdlcNQOujPdbuOV75OJmCMvjy0UMhDlldDDfeTw=s48-c-k-c0x00ffffff-no-rj',
      'authorChannelUrl': 'http://www.youtube.com/@Sandy-q1p',
      'authorChannelId': {'value': 'UCeqFFzQcnFV3N2KKttZoXNw'},
      'canRate': True,
      'viewerRating': 'none',
      'likeCount': 0,
      'publishedAt': '2025-08-19T21:22:59Z',
      'updatedAt': '2025-08-19T21:22:59Z'}},
    'canReply': True,
    'totalReplyCount': 0,
    'isPublic': True}},
  {'kind': 'youtube#commentThread',
   'etag': 'COwSJKMhxP8WbPapQTSP6vFoQ1w',
   'id': 'Ugx74_UBJfqi39ZkihV4AaABAg',
   'snippet': {'channelId': 'UCvRAX-ujvZ0eTMLGG2vki9w',
    'videoId': '84-cHoF2-KM',
    'topLevelComment': {'kind': 'youtube#comment',
     'etag': 'NZVMfNWYeKWecCVzYWGPRjpTv6A',
     'id': 'Ugx74_UBJfqi39ZkihV4AaABAg',
     'snippet': {'channelId': 'UCvRAX-ujvZ0eTMLGG2vki9w',
      'videoId': '84-cHoF2-KM',
      'textDisplay': 'back in the 1960s the US Navy &#39;owned&#39; the South China Sea. We even sailed between between Hainan Island the ChiComm mainland. I guess the US Navy has lost its spine.',
      'textOriginal': "back in the 1960s the US Navy 'owned' the South China Sea. We even sailed between between Hainan Island the ChiComm mainland. I guess the US Navy has lost its spine.",
      'authorDisplayName': '@hevadhu9513',
      'authorProfileImageUrl': 'https://yt3.ggpht.com/ytc/AIdro_l_89c5gDKYWPHeNj09kpyNyDmLXgzy6IsPe_vnNlE=s48-c-k-c0x00ffffff-no-rj',
      'authorChannelUrl': 'http://www.youtube.com/@hevadhu9513',
      'authorChannelId': {'value': 'UCIZstleyHLy6Agqe6P3u4VQ'},
      'canRate': True,
      'viewerRating': 'none',
      'likeCount': 0,
      'publishedAt': '2025-08-19T10:15:51Z',
      'updatedAt': '2025-08-19T10:15:51Z'}},
    'canReply': True,
    'totalReplyCount': 0,
    'isPublic': True}},
  {'kind': 'youtube#commentThread',
   'etag': 'mmBSv-FudMpJ5waLfRqscMKQD74',
   'id': 'UgxgNu6gfEBJgnyZCPZ4AaABAg',
   'snippet': {'channelId': 'UCvRAX-ujvZ0eTMLGG2vki9w',
    'videoId': '84-cHoF2-KM',
    'topLevelComment': {'kind': 'youtube#comment',
     'etag': 'GqDcugjJBZhmPZJjnvW27Ko61pw',
     'id': 'UgxgNu6gfEBJgnyZCPZ4AaABAg',
     'snippet': {'channelId': 'UCvRAX-ujvZ0eTMLGG2vki9w',
      'videoId': '84-cHoF2-KM',
      'textDisplay': 'Huli man daw at magaling ay<br>huli pa rin ang mga imperialistang puti. <br>Nagbanggaan ang mga ganid na komunistang chekwa. 😂😂😂',
      'textOriginal': 'Huli man daw at magaling ay\nhuli pa rin ang mga imperialistang puti. \nNagbanggaan ang mga ganid na komunistang chekwa. 😂😂😂',
      'authorDisplayName': '@AbnerPangilinan-h7r',
      'authorProfileImageUrl': 'https://yt3.ggpht.com/ytc/AIdro_lO1bg78qyz0HR_ZIH8s5qeSfzYr9fVSd1DukOaqgMnQ42rwYpPYWufcdbL9Z9Zby0O7g=s48-c-k-c0x00ffffff-no-rj',
      'authorChannelUrl': 'http://www.youtube.com/@AbnerPangilinan-h7r',
      'authorChannelId': {'value': 'UCFBCMda3awPJrEx5yIV9ODA'},
      'canRate': True,
      'viewerRating': 'none',
      'likeCount': 0,
      'publishedAt': '2025-08-19T05:37:42Z',
      'updatedAt': '2025-08-19T05:37:42Z'}},
    'canReply': True,
    'totalReplyCount': 0,
    'isPublic': True}},
  {'kind': 'youtube#commentThread',
   'etag': 'et7FyAkqOkj_ryEt_ZA0Fn3bFao',
   'id': 'UgwWubz2uStcGrTce-V4AaABAg',
   'snippet': {'channelId': 'UCvRAX-ujvZ0eTMLGG2vki9w',
    'videoId': '84-cHoF2-KM',
    'topLevelComment': {'kind': 'youtube#comment',
     'etag': 'W3up17mIansl4NRhHkMaYdVBVHU',
     'id': 'UgwWubz2uStcGrTce-V4AaABAg',
     'snippet': {'channelId': 'UCvRAX-ujvZ0eTMLGG2vki9w',
      'videoId': '84-cHoF2-KM',
      'textDisplay': 'Good news!',
      'textOriginal': 'Good news!',
      'authorDisplayName': '@RFR-003',
      'authorProfileImageUrl': 'https://yt3.ggpht.com/ytc/AIdro_lawf9yWTQpDKE0MLo3587nhlwH_ppxDQse0Bw_-WWV25kHUsQnoRSTBnBBFdxj69wZBg=s48-c-k-c0x00ffffff-no-rj',
      'authorChannelUrl': 'http://www.youtube.com/@RFR-003',
      'authorChannelId': {'value': 'UCpRJwi5jIy_7_9C4ajuf9Yw'},
      'canRate': True,
      'viewerRating': 'none',
      'likeCount': 2,
      'publishedAt': '2025-08-19T00:36:19Z',
      'updatedAt': '2025-08-19T00:36:55Z'}},
    'canReply': True,
    'totalReplyCount': 0,
    'isPublic': True}},
  {'kind': 'youtube#commentThread',
   'etag': 'ad9ASMzZzoB-cj5zudcTbjZ_-zo',
   'id': 'UgxhUkrBY2xkRYAfprt4AaABAg',
   'snippet': {'channelId': 'UCvRAX-ujvZ0eTMLGG2vki9w',
    'videoId': '84-cHoF2-KM',
    'topLevelComment': {'kind': 'youtube#comment',
     'etag': 'ZfUGOvmqFMsgqZdzcirxko1WVBY',
     'id': 'UgxhUkrBY2xkRYAfprt4AaABAg',
     'snippet': {'channelId': 'UCvRAX-ujvZ0eTMLGG2vki9w',
      'videoId': '84-cHoF2-KM',
      'textDisplay': 'About time',
      'textOriginal': 'About time',
      'authorDisplayName': '@JohnSilveira-p7k',
      'authorProfileImageUrl': 'https://yt3.ggpht.com/ytc/AIdro_mXl5vEZetSFCfuG2B7_VLqc38fE5TVJMtL_CGIeMUbdXJf55quvy5KONcX81xCv66Llw=s48-c-k-c0x00ffffff-no-rj',
      'authorChannelUrl': 'http://www.youtube.com/@JohnSilveira-p7k',
      'authorChannelId': {'value': 'UC01t05GfAJQrMSK0UrNaSFw'},
      'canRate': True,
      'viewerRating': 'none',
      'likeCount': 0,
      'publishedAt': '2025-08-18T21:08:55Z',
      'updatedAt': '2025-08-18T21:08:55Z'}},
    'canReply': True,
    'totalReplyCount': 0,
    'isPublic': True}},
  {'kind': 'youtube#commentThread',
   'etag': 'W9qbQ3SvzHv0klrddO4jqOPZi7s',
   'id': 'Ugz57iOTlwAwp0Tadf54AaABAg',
   'snippet': {'channelId': 'UCvRAX-ujvZ0eTMLGG2vki9w',
    'videoId': '84-cHoF2-KM',
    'topLevelComment': {'kind': 'youtube#comment',
     'etag': 'q1V8G43H41T2O9VXldqB8FkXAAc',
     'id': 'Ugz57iOTlwAwp0Tadf54AaABAg',
     'snippet': {'channelId': 'UCvRAX-ujvZ0eTMLGG2vki9w',
      'videoId': '84-cHoF2-KM',
      'textDisplay': 'ini Easy easy Lang Kase Nang Mga Bansang Communists Ang PhiLippines... ALam Kase NiLa Na Mahirap Na Bansa At Bagsak Dati Ang Economy, At ALam NiLa Na WaLang Kakayahan Na BumiLi Nang Mga Modernisadong Weapons Ang PhiLippines, Kya Sina SamantaLa NiLa, ALam Kase Nang Mga Bansang Communists Noon Pa Na WaLang MaLaLakas Na Armas Ang Bansang PhiLippines.',
      'textOriginal': 'ini Easy easy Lang Kase Nang Mga Bansang Communists Ang PhiLippines... ALam Kase NiLa Na Mahirap Na Bansa At Bagsak Dati Ang Economy, At ALam NiLa Na WaLang Kakayahan Na BumiLi Nang Mga Modernisadong Weapons Ang PhiLippines, Kya Sina SamantaLa NiLa, ALam Kase Nang Mga Bansang Communists Noon Pa Na WaLang MaLaLakas Na Armas Ang Bansang PhiLippines.',
      'authorDisplayName': '@HelenAnthony-b9z',
      'authorProfileImageUrl': 'https://yt3.ggpht.com/ytc/AIdro_lL3a2p2kIBbgir_m-rckUr5pkGbwR1ycPtuGmQT3WUuLmQz_5O7czOh4UrUqhwiCJ0IA=s48-c-k-c0x00ffffff-no-rj',
      'authorChannelUrl': 'http://www.youtube.com/@HelenAnthony-b9z',
      'authorChannelId': {'value': 'UCvDywJTVt6erILAEQdGgDJQ'},
      'canRate': True,
      'viewerRating': 'none',
      'likeCount': 0,
      'publishedAt': '2025-08-18T08:10:23Z',
      'updatedAt': '2025-08-18T08:10:23Z'}},
    'canReply': True,
    'totalReplyCount': 0,
    'isPublic': True}},
  {'kind': 'youtube#commentThread',
   'etag': '9JWJPbxg89abHPzh2MAfTfBlCbU',
   'id': 'UgwWKEnHVfMo4a0-yB94AaABAg',
   'snippet': {'channelId': 'UCvRAX-ujvZ0eTMLGG2vki9w',
    'videoId': '84-cHoF2-KM',
    'topLevelComment': {'kind': 'youtube#comment',
     'etag': 'av1tagmPSPaXBuWS_K9NnwRzu_o',
     'id': 'UgwWKEnHVfMo4a0-yB94AaABAg',
     'snippet': {'channelId': 'UCvRAX-ujvZ0eTMLGG2vki9w',
      'videoId': '84-cHoF2-KM',
      'textDisplay': 'Way to go Shame China nlamesy Philippines for their own wrong doings',
      'textOriginal': 'Way to go Shame China nlamesy Philippines for their own wrong doings',
      'authorDisplayName': '@Mercedes-p3e',
      'authorProfileImageUrl': 'https://yt3.ggpht.com/ytc/AIdro_nQnix-VeJ6EdB4XIG9FFgrkb8_vpSDP2Ft1Cp8cNbPAPogyXsBLaYw96po1fV2IWNUFw=s48-c-k-c0x00ffffff-no-rj',
      'authorChannelUrl': 'http://www.youtube.com/@Mercedes-p3e',
      'authorChannelId': {'value': 'UCy6jvxbSvyOXNAQ5Q9pLX_w'},
      'canRate': True,
      'viewerRating': 'none',
      'likeCount': 0,
      'publishedAt': '2025-08-18T06:54:35Z',
      'updatedAt': '2025-08-18T06:54:35Z'}},
    'canReply': True,
    'totalReplyCount': 0,
    'isPublic': True}},
  {'kind': 'youtube#commentThread',
   'etag': 'BXFfkxA_GDFVHdANg-30_kgWf8o',
   'id': 'UgzH_TsGoA0-QkuxE2J4AaABAg',
   'snippet': {'channelId': 'UCvRAX-ujvZ0eTMLGG2vki9w',
    'videoId': '84-cHoF2-KM',
    'topLevelComment': {'kind': 'youtube#comment',
     'etag': '65wl0BAGXcVNX_7J-8fAm3q-z14',
     'id': 'UgzH_TsGoA0-QkuxE2J4AaABAg',
     'snippet': {'channelId': 'UCvRAX-ujvZ0eTMLGG2vki9w',
      'videoId': '84-cHoF2-KM',
      'textDisplay': '😂Chinese run from USN😂 wat a chicken 🐔 China 😂',
      'textOriginal': '😂Chinese run from USN😂 wat a chicken 🐔 China 😂',
      'authorDisplayName': '@commiepig8016',
      'authorProfileImageUrl': 'https://yt3.ggpht.com/ytc/AIdro_kIacD06lXrjUNO9YOw1PYSEiV9bs-4RP6-g2NPYGE=s48-c-k-c0x00ffffff-no-rj',
      'authorChannelUrl': 'http://www.youtube.com/@commiepig8016',
      'authorChannelId': {'value': 'UCsoO9dhyeC-nbLtGlq6s3_g'},
      'canRate': True,
      'viewerRating': 'none',
      'likeCount': 1,
      'publishedAt': '2025-08-18T06:00:59Z',
      'updatedAt': '2025-08-18T06:00:59Z'}},
    'canReply': True,
    'totalReplyCount': 0,
    'isPublic': True}},
  {'kind': 'youtube#commentThread',
   'etag': 'OHtpEBIjXECqfkGGXgCnwB3vHL0',
   'id': 'Ugwx4qY2edRnCEnTDx54AaABAg',
   'snippet': {'channelId': 'UCvRAX-ujvZ0eTMLGG2vki9w',
    'videoId': '84-cHoF2-KM',
    'topLevelComment': {'kind': 'youtube#comment',
     'etag': 'B2AIKMeBmomALNT0fIGbt1tyVVE',
     'id': 'Ugwx4qY2edRnCEnTDx54AaABAg',
     'snippet': {'channelId': 'UCvRAX-ujvZ0eTMLGG2vki9w',
      'videoId': '84-cHoF2-KM',
      'textDisplay': 'China duwag pag nandiyan na malalaking aso',
      'textOriginal': 'China duwag pag nandiyan na malalaking aso',
      'authorDisplayName': '@leechrec',
      'authorProfileImageUrl': 'https://yt3.ggpht.com/ytc/AIdro_leFFe8KMeL6dviJz4lflNtiouNm3lwAszN8UUFbfSwdMLOPurEgsecMSCzM5JDe-AUAA=s48-c-k-c0x00ffffff-no-rj',
      'authorChannelUrl': 'http://www.youtube.com/@leechrec',
      'authorChannelId': {'value': 'UCbJ3BsMPpuGt7EJLJVXmw-w'},
      'canRate': True,
      'viewerRating': 'none',
      'likeCount': 0,
      'publishedAt': '2025-08-18T03:21:43Z',
      'updatedAt': '2025-08-18T03:21:43Z'}},
    'canReply': True,
    'totalReplyCount': 0,
    'isPublic': True}},
  {'kind': 'youtube#commentThread',
   'etag': '2JXclR4UoXx0cmfnqWO85Y1ljfo',
   'id': 'Ugw9Eu7qa0-1Utr3HY54AaABAg',
   'snippet': {'channelId': 'UCvRAX-ujvZ0eTMLGG2vki9w',
    'videoId': '84-cHoF2-KM',
    'topLevelComment': {'kind': 'youtube#comment',
     'etag': 'gQlZvkzel6pwEa16TGYY9O4Nwpc',
     'id': 'Ugw9Eu7qa0-1Utr3HY54AaABAg',
     'snippet': {'channelId': 'UCvRAX-ujvZ0eTMLGG2vki9w',
      'videoId': '84-cHoF2-KM',
      'textDisplay': 'Pag si Sara Dutae ang mamumuno walang US na makakapasok sa territoryo natin kundi mga Chinese tandaan nyo yan, Lalong magugutom ang mga mangingisda, at lalong tataas ang mga presyo ng isda.',
      'textOriginal': 'Pag si Sara Dutae ang mamumuno walang US na makakapasok sa territoryo natin kundi mga Chinese tandaan nyo yan, Lalong magugutom ang mga mangingisda, at lalong tataas ang mga presyo ng isda.',
      'authorDisplayName': '@Boldjack101',
      'authorProfileImageUrl': 'https://yt3.ggpht.com/vbYiJkSlBLsxu1NOFK_T3tBnXehmJKTbQvXXDM3246XJJuY4AsSfg_0eeS3e3lEXbwFs0oo_xw=s48-c-k-c0x00ffffff-no-rj',
      'authorChannelUrl': 'http://www.youtube.com/@Boldjack101',
      'authorChannelId': {'value': 'UCeElABh1n1qOaH6sIwRCHKw'},
      'canRate': True,
      'viewerRating': 'none',
      'likeCount': 0,
      'publishedAt': '2025-08-18T00:33:58Z',
      'updatedAt': '2025-08-18T00:33:58Z'}},
    'canReply': True,
    'totalReplyCount': 0,
    'isPublic': True}},
  {'kind': 'youtube#commentThread',
   'etag': 'X0qVEZOMm4StOUX3TBUJJjHHOMg',
   'id': 'UgxKsk3BA9eMXHsK80t4AaABAg',
   'snippet': {'channelId': 'UCvRAX-ujvZ0eTMLGG2vki9w',
    'videoId': '84-cHoF2-KM',
    'topLevelComment': {'kind': 'youtube#comment',
     'etag': 'n3uaG6kJWvZmgmIFCi8nCJTO3_s',
     'id': 'UgxKsk3BA9eMXHsK80t4AaABAg',
     'snippet': {'channelId': 'UCvRAX-ujvZ0eTMLGG2vki9w',
      'videoId': '84-cHoF2-KM',
      'textDisplay': 'God bless and protect Philippines 🙏🙏🙏',
      'textOriginal': 'God bless and protect Philippines 🙏🙏🙏',
      'authorDisplayName': '@feflores7851',
      'authorProfileImageUrl': 'https://yt3.ggpht.com/ytc/AIdro_mA2AVFV-qavNRylO-8a4Gy-Z6PmCR1F_ZClH9D2RWiGO4aLpoBwvnFubP3fe06ChSeLA=s48-c-k-c0x00ffffff-no-rj',
      'authorChannelUrl': 'http://www.youtube.com/@feflores7851',
      'authorChannelId': {'value': 'UC6pS3pS24ujs0vSB3D7gohw'},
      'canRate': True,
      'viewerRating': 'none',
      'likeCount': 0,
      'publishedAt': '2025-08-17T22:33:09Z',
      'updatedAt': '2025-08-17T22:33:09Z'}},
    'canReply': True,
    'totalReplyCount': 0,
    'isPublic': True}},
  {'kind': 'youtube#commentThread',
   'etag': 'zretDSiIcCfC1z8xF99fKtKElPM',
   'id': 'UgwQIvbUFT1FGEvSKQJ4AaABAg',
   'snippet': {'channelId': 'UCvRAX-ujvZ0eTMLGG2vki9w',
    'videoId': '84-cHoF2-KM',
    'topLevelComment': {'kind': 'youtube#comment',
     'etag': '3tPprN-dprWKo4Un8s3Ngl-8dns',
     'id': 'UgwQIvbUFT1FGEvSKQJ4AaABAg',
     'snippet': {'channelId': 'UCvRAX-ujvZ0eTMLGG2vki9w',
      'videoId': '84-cHoF2-KM',
      'textDisplay': 'Thanks Uncle Sam',
      'textOriginal': 'Thanks Uncle Sam',
      'authorDisplayName': '@ericcaesarpalafox1551',
      'authorProfileImageUrl': 'https://yt3.ggpht.com/ytc/AIdro_kzN4lSrCd4KOs7evpNyfM7eOP9-WNErwzJLZNeo54=s48-c-k-c0x00ffffff-no-rj',
      'authorChannelUrl': 'http://www.youtube.com/@ericcaesarpalafox1551',
      'authorChannelId': {'value': 'UCTAvQGxFlKo_hN2OI00abXg'},
      'canRate': True,
      'viewerRating': 'none',
      'likeCount': 0,
      'publishedAt': '2025-08-17T22:28:22Z',
      'updatedAt': '2025-08-17T22:28:22Z'}},
    'canReply': True,
    'totalReplyCount': 0,
    'isPublic': True}},
  {'kind': 'youtube#commentThread',
   'etag': 'Yt9hNzB5RSTFJbgT_BJU5Kq_oAc',
   'id': 'UgxBdGr_elFP-AG1Nd14AaABAg',
   'snippet': {'channelId': 'UCvRAX-ujvZ0eTMLGG2vki9w',
    'videoId': '84-cHoF2-KM',
    'topLevelComment': {'kind': 'youtube#comment',
     'etag': 'MaR090I-fFlASsi0Ai8UiHzj78o',
     'id': 'UgxBdGr_elFP-AG1Nd14AaABAg',
     'snippet': {'channelId': 'UCvRAX-ujvZ0eTMLGG2vki9w',
      'videoId': '84-cHoF2-KM',
      'textDisplay': 'In a short time China will react in a way that causes massive tensions with the U.S. and the U.S. will put all Chinese ships at rest at the bottom of the ocean!  The Dragons head will be decapitated and China vulnerable to at will missle strikes on its homeland bases!   China is out matched with weaponry they cant defend themselves against! China is new to the war world but with its boldness and unrelenting defying of the higher power will fall!  The Dragons  will rest at the bottom of the sea!  For we are America the authority of water we will set you free to knowing the outcome of pure destruction!  Tread lite China! You know not what you will deal with!!',
      'textOriginal': 'In a short time China will react in a way that causes massive tensions with the U.S. and the U.S. will put all Chinese ships at rest at the bottom of the ocean!  The Dragons head will be decapitated and China vulnerable to at will missle strikes on its homeland bases!   China is out matched with weaponry they cant defend themselves against! China is new to the war world but with its boldness and unrelenting defying of the higher power will fall!  The Dragons  will rest at the bottom of the sea!  For we are America the authority of water we will set you free to knowing the outcome of pure destruction!  Tread lite China! You know not what you will deal with!!',
      'authorDisplayName': '@nathanmozley5959',
      'authorProfileImageUrl': 'https://yt3.ggpht.com/ytc/AIdro_mKGH0X7pDAZIbKpAI61oFGi-2meWCnRzfT-y4wgCY=s48-c-k-c0x00ffffff-no-rj',
      'authorChannelUrl': 'http://www.youtube.com/@nathanmozley5959',
      'authorChannelId': {'value': 'UCTz0_sAwac8LKOhNlINr3xw'},
      'canRate': True,
      'viewerRating': 'none',
      'likeCount': 0,
      'publishedAt': '2025-08-17T06:41:43Z',
      'updatedAt': '2025-08-17T06:41:43Z'}},
    'canReply': True,
    'totalReplyCount': 0,
    'isPublic': True}},
  {'kind': 'youtube#commentThread',
   'etag': 'LgHuWBCyGMh_AAMa6P_IwXrSngw',
   'id': 'UgxC_YotKRfWvlS2ceV4AaABAg',

We can see that the contents are quite long, but if we take the time to analyze it, we'll realize it's really just a nested dictionary with the following keys: `kind`, `etag`, `nextPageToken`, `pageInfo`, and `items`.

The values in `pageInfo` tell us how many results are included in this set--in this case, 50 comments and their corresponding replies. The 50 comments are contained as dictionaries within the `items` key.

To confirm, let's check the length of the `items`.

In [ ]:
len(video_response['items'])

100

## Inspecting a single YouTube comment

Now, let's try and see what each item in the response looks like. Let's examine the 1st item in the list.

In [ ]:
video_response['items'][4]

{'kind': 'youtube#commentThread',
 'etag': 'mmBSv-FudMpJ5waLfRqscMKQD74',
 'id': 'UgxgNu6gfEBJgnyZCPZ4AaABAg',
 'snippet': {'channelId': 'UCvRAX-ujvZ0eTMLGG2vki9w',
  'videoId': '84-cHoF2-KM',
  'topLevelComment': {'kind': 'youtube#comment',
   'etag': 'GqDcugjJBZhmPZJjnvW27Ko61pw',
   'id': 'UgxgNu6gfEBJgnyZCPZ4AaABAg',
   'snippet': {'channelId': 'UCvRAX-ujvZ0eTMLGG2vki9w',
    'videoId': '84-cHoF2-KM',
    'textDisplay': 'Huli man daw at magaling ay<br>huli pa rin ang mga imperialistang puti. <br>Nagbanggaan ang mga ganid na komunistang chekwa. 😂😂😂',
    'textOriginal': 'Huli man daw at magaling ay\nhuli pa rin ang mga imperialistang puti. \nNagbanggaan ang mga ganid na komunistang chekwa. 😂😂😂',
    'authorDisplayName': '@AbnerPangilinan-h7r',
    'authorProfileImageUrl': 'https://yt3.ggpht.com/ytc/AIdro_lO1bg78qyz0HR_ZIH8s5qeSfzYr9fVSd1DukOaqgMnQ42rwYpPYWufcdbL9Z9Zby0O7g=s48-c-k-c0x00ffffff-no-rj',
    'authorChannelUrl': 'http://www.youtube.com/@AbnerPangilinan-h7r',
    'authorChannelId': {'value': 'UCFBCMda3awPJrEx5yIV9ODA'},
    'canRate': True,
    'viewerRating': 'none',
    'likeCount': 0,
    'publishedAt': '2025-08-19T05:37:42Z',
    'updatedAt': '2025-08-19T05:37:42Z'}},
  'canReply': True,
  'totalReplyCount': 0,
  'isPublic': True}}

We can extract the following
- textDisplay
- id
- publishedAt
- textOriginal

Then add additional features
- likeCount
- repliedParentId

In [ ]:
# For the original comment
print(
  f'https://www.youtube.com/watch?v={video_id}&lc={video_response["items"][0]["snippet"]["topLevelComment"]["id"]}'
)
print(video_response['items'][0]['snippet']['topLevelComment']['snippet']['textDisplay'])
print(video_response['items'][0]['snippet']['topLevelComment']['snippet']['publishedAt'])
print(video_response['items'][0]['snippet']['topLevelComment']['snippet']['textOriginal'])
print(video_response['items'][0]['snippet']['topLevelComment']['snippet']['likeCount'])
# No repliedParentId

https://www.youtube.com/watch?v=84-cHoF2-KM&lc=UgxjnwJEowNi2_gDy2t4AaABAg
US ain&#39;t going to defend you when the real battle begins.  Filipino should stop trying acting tough. Filipino are just little Chihuahua.
2025-08-23T01:58:32Z
US ain't going to defend you when the real battle begins.  Filipino should stop trying acting tough. Filipino are just little Chihuahua.
0

## Extracting replies from comment

If `totalReplyCount` is greater than 0, we can extract the replies to the comment.
In the `video_response` object, we can see that the replies are nested within the `comments` key. HOWEVER, this method does not include all replies.

As such, we have to use the `comments.list` method to get all replies to a comment.
Refer to [CommentsList](https://developers.google.com/youtube/v3/docs/comments/list) document for more information.

In [ ]:
video_response['items'][-1]['snippet']['totalReplyCount']

0

In [ ]:
len(
  video_response['items'][-1]['replies']['comments']
)

KeyError: 'replies'

Using a similar process, we can also extract the one reply to this comment. We know there's three replies because of the value of the `totalReplyCount` key.

In [ ]:
comment_number = -1
total_reply_count = video_response['items'][comment_number]['snippet']['totalReplyCount']

if total_reply_count > 0:
  parent_id = video_response['items'][comment_number]['snippet']['topLevelComment']['id']

  replies = youtube.comments().list(
    part='snippet', parentId=parent_id, maxResults=50
  ).execute()

  for reply in replies['items']:
    print(
      f"https://www.youtube.com/watch?v={video_id}&lc={reply['id']}"
    )
    print(reply['snippet']['textDisplay'])
    print(reply['snippet']['publishedAt'])
    print(reply['snippet']['textOriginal'])
    print(reply['snippet']['likeCount'])
    print(reply['snippet']['parentId'])
    print()

## Automating the extraction

Now that we know how to extract individual comments from YouTube videos, we need to figure out how we can automate this process so that we can build a corpus of comments without manually getting comments and replies one by one.

To do this, we rely on the following:
1.   the consistency of the nested dictionary results structure of the YouTube API
2.   Python loops
3.   page tokens

Let's work on the first two.

First, we create a list where we will store all scraped data.

In [ ]:
comments = []

Then, we use loops to iterate through the contents of `video_response`.

In [ ]:
# iterate through items
for item in video_response['items']:

  # extract comment from each item
  comment = item['snippet']['topLevelComment']['snippet']

  # append comment to list of comments
  comments.append([
    comment['textDisplay'],
    f'https://www.youtube.com/watch?v={video_id}&lc={item["snippet"]["topLevelComment"]["id"]}',
    comment['publishedAt'],
    comment['textOriginal'],
    comment['likeCount'],
    np.nan
  ])

  # count number of replies
  total_reply_count = item['snippet']['totalReplyCount']

  # if there is at least one reply
  if total_reply_count > 0:
    parent_id = item["snippet"]["topLevelComment"]["id"]

    replies = youtube.comments().list(
      part='snippet', parentId=parent_id, maxResults=50
    ).execute()

    # iterate through the replies
    for reply in replies['items']:
      # extract text from each reply
      # append reply to list of comments
      replyBody = reply['snippet']
      comments.append([
        replyBody['textDisplay'],
        f"https://www.youtube.com/watch?v={video_id}&lc={reply['id']}",
        replyBody['publishedAt'],
        replyBody['textOriginal'],
        replyBody['likeCount'],
        replyBody['parentId']
      ])

In [ ]:
youtube_corpus = pd.DataFrame(
  comments, columns=['title', 'link', 'date_published', 'text', 'like_count', 'reply_parent_id'])
youtube_corpus

,title,link,date_published,text,like_count,reply_parent_id
0,US ain&#39;t going to defend you when the real...,https://www.youtube.com/watch?v=84-cHoF2-KM&lc...,2025-08-23T01:58:32Z,US ain't going to defend you when the real bat...,0,NaN
1,Chinese ships should be easy to sink if built ...,https://www.youtube.com/watch?v=84-cHoF2-KM&lc...,2025-08-20T20:31:17Z,Chinese ships should be easy to sink if built ...,0,NaN
2,Erase china from world map,https://www.youtube.com/watch?v=84-cHoF2-KM&lc...,2025-08-19T21:22:59Z,Erase china from world map,0,NaN
3,back in the 1960s the US Navy &#39;owned&#39; ...,https://www.youtube.com/watch?v=84-cHoF2-KM&lc...,2025-08-19T10:15:51Z,back in the 1960s the US Navy 'owned' the Sout...,0,NaN
4,Huli man daw at magaling ay<br>huli pa rin ang...,https://www.youtube.com/watch?v=84-cHoF2-KM&lc...,2025-08-19T05:37:42Z,Huli man daw at magaling ay\nhuli pa rin ang m...,0,NaN
...,...,...,...,...,...,...
107,"GOD BLESS PHILIPPINES,USA,JSPAN,PBBM,SEC GIBO....",https://www.youtube.com/watch?v=84-cHoF2-KM&lc...,2025-08-14T02:13:07Z,"GOD BLESS PHILIPPINES,USA,JSPAN,PBBM,SEC GIBO....",1,NaN
108,"Ang Pinas ay alipin pa rin ng poon nyang Kano,...",https://www.youtube.com/watch?v=84-cHoF2-KM&lc...,2025-08-14T02:12:38Z,"Ang Pinas ay alipin pa rin ng poon nyang Kano,...",0,NaN
109,Heil Ping,https://www.youtube.com/watch?v=84-cHoF2-KM&lc...,2025-08-14T02:10:46Z,Heil Ping,0,NaN
110,USA will protect us,https://www.youtube.com/watch?v=84-cHoF2-KM&lc...,2025-08-14T02:05:04Z,USA will protect us,0,NaN
111,Wag magalit si pro China na Duterte,https://www.youtube.com/watch?v=84-cHoF2-KM&lc...,2025-08-14T01:59:28Z,Wag magalit si pro China na Duterte,0,NaN

## Handling next page with page tokens

Let's take another example with more comments.

We'll have a list of 50 or so comments from the video.

However, if we check the video's comments section, we'll see that there are 128 comments in the video.

So how can we extract more comments? That's where `pageToken` comes in.

In [ ]:
video_id = '84-cHoF2-KM'
video_response = youtube.commentThreads().list(
  videoId=video_id, part='snippet,replies', maxResults=50,
  order='time'
).execute()

# iterate through items
for item in video_response['items']:

  # extract comment from each item
  comment = item['snippet']['topLevelComment']['snippet']

  # append comment to list of comments
  comments.append([
    comment['textDisplay'],
    f'https://www.youtube.com/watch?v={video_id}&lc={item["snippet"]["topLevelComment"]["id"]}',
    comment['publishedAt'],
    comment['textOriginal'],
    comment['likeCount'],
    np.nan
  ])

  # count number of replies
  total_reply_count = item['snippet']['totalReplyCount']

  # if there is at least one reply
  if total_reply_count > 0:
    parent_id = item["snippet"]["topLevelComment"]["id"]

    replies = youtube.comments().list(
      part='snippet', parentId=parent_id, maxResults=50
    ).execute()

    # iterate through the replies
    for reply in replies['items']:
      # extract text from each reply
      # append reply to list of comments
      replyBody = reply['snippet']
      comments.append([
        replyBody['textDisplay'],
        f"https://www.youtube.com/watch?v={video_id}&lc={reply['id']}",
        replyBody['publishedAt'],
        replyBody['textOriginal'],
        replyBody['likeCount'],
        replyBody['parentId']
      ])

youtube_corpus = pd.DataFrame(
  comments, columns=['title', 'link', 'date_published', 'text', 'like_count', 'reply_parent_id'])
youtube_corpus

,title,link,date_published,text,like_count,reply_parent_id
0,US ain&#39;t going to defend you when the real...,https://www.youtube.com/watch?v=84-cHoF2-KM&lc...,2025-08-23T01:58:32Z,US ain't going to defend you when the real bat...,0,NaN
1,Chinese ships should be easy to sink if built ...,https://www.youtube.com/watch?v=84-cHoF2-KM&lc...,2025-08-20T20:31:17Z,Chinese ships should be easy to sink if built ...,0,NaN
2,Erase china from world map,https://www.youtube.com/watch?v=84-cHoF2-KM&lc...,2025-08-19T21:22:59Z,Erase china from world map,0,NaN
3,back in the 1960s the US Navy &#39;owned&#39; ...,https://www.youtube.com/watch?v=84-cHoF2-KM&lc...,2025-08-19T10:15:51Z,back in the 1960s the US Navy 'owned' the Sout...,0,NaN
4,Huli man daw at magaling ay<br>huli pa rin ang...,https://www.youtube.com/watch?v=84-cHoF2-KM&lc...,2025-08-19T05:37:42Z,Huli man daw at magaling ay\nhuli pa rin ang m...,0,NaN
...,...,...,...,...,...,...
159,"IT&#39;S LIKENED TO BASKETBALL, MAN. TO. MAN ...",https://www.youtube.com/watch?v=84-cHoF2-KM&lc...,2025-08-14T09:16:47Z,"IT'S LIKENED TO BASKETBALL, MAN. TO. MAN DEFF...",0,NaN
160,Wkwkwkw kocak,https://www.youtube.com/watch?v=84-cHoF2-KM&lc...,2025-08-14T09:04:42Z,Wkwkwkw kocak,0,NaN
161,People Liberation Army?<br><br>More like Peopl...,https://www.youtube.com/watch?v=84-cHoF2-KM&lc...,2025-08-14T08:35:00Z,People Liberation Army?\n\nMore like People Lu...,0,NaN
162,They hit each other these Chinese..,https://www.youtube.com/watch?v=84-cHoF2-KM&lc...,2025-08-14T07:37:49Z,They hit each other these Chinese..,0,NaN
163,CHINA SHOULD REFRAIN FROM ASKING ANY NATION T...,https://www.youtube.com/watch?v=84-cHoF2-KM&lc...,2025-08-14T07:28:33Z,CHINA SHOULD REFRAIN FROM ASKING ANY NATION T...,0,NaN

If we return to the contents of `video_response`, we'll see that one of its keys is the `nextPageToken` key. This key is like an ID that distinguishes the pages within a set of search results--in this case, the comments section of the video.

If we add a `pageToken` argument to our `youtube.commentThreads().list()` method, you'll see that we will get different results from the previous one.

In [ ]:
# Check whether video_response has `nextPageToken`
video_response['nextPageToken']

'Z2V0X25ld2VzdF9maXJzdC0tQ2dnSWdBUVZGN2ZST0JJRkNLZ2dHQUFTQlFpSElCZ0FFZ1VJaUNBWUFCSUZDSWtnR0FBU0JRaWRJQmdCSWc0S0RBaWhvUGJFQmhDZ2k5WFNBUQ=='

In [ ]:
# Make the same request but with the `nextPageToken`
video_response_2 = youtube.commentThreads().list(
  videoId=video_id, part='snippet,replies', maxResults=50,
  order='time',
  pageToken=video_response['nextPageToken']
).execute()

In [ ]:
video_response_2['items'][0]['snippet']['topLevelComment']['snippet']['textDisplay']

'Intimidatory tactics by bullies!'

Let's now incorporate `pageToken` into our loop.

In [ ]:
# how many comments do we want
no_comments = 500

# re-initialize list of YouTube comments
comments = []
youtube_corpus = None

video_id = '0v1XHgWyIvU'  # more comments
# video_id = 'yfoq-0gGTLM' # fewer comments

# get first page of the comments
video_response = youtube.commentThreads().list(
  videoId=video_id, part='snippet,replies', maxResults=50,
  order='time', moderationStatus='published'
).execute()

while len(comments) < no_comments:
  # iterate through items
  for item in video_response['items']:
    ##### Parent Comments #####
    # extract comment from each item
    comment = item['snippet']['topLevelComment']['snippet']

    # append comment to list of comments
    comments.append([
      comment['textDisplay'],
      f'https://www.youtube.com/watch?v={video_id}&lc={item["snippet"]["topLevelComment"]["id"]}',
      comment['publishedAt'],
      comment['textOriginal'],
      comment['likeCount'],
      np.nan
    ])

    ##### Reply Comments #####
    # count number of replies
    total_reply_count = item['snippet']['totalReplyCount']

    # if there is at least one reply
    if total_reply_count > 0:
      parent_id = item["snippet"]["topLevelComment"]["id"]

      replies = youtube.comments().list(
        part='snippet',
        parentId=parent_id
      ).execute()

      # iterate through the replies
      for reply in replies['items']:
        # extract text from each reply
        # append reply to list of comments
        replyBody = reply['snippet']
        comments.append([
          replyBody['textDisplay'],
          f"https://www.youtube.com/watch?v={video_id}&lc={reply['id']}",
          replyBody['publishedAt'],
          replyBody['textOriginal'],
          replyBody['likeCount'],
          replyBody['parentId']
        ])

  ##### Next Page #####
  # print number of comments
  print(str(len(comments)) + ' comments in list')

  # if there is a next page to the comment result
  if 'nextPageToken' in video_response:
    # notify that next page has been found
    print('Next comment page found. Now extracting data. \n')

    # get the next page
    video_response = youtube.commentThreads().list(
      videoId=video_id, part='snippet,replies', maxResults=50,
      order='time', pageToken=video_response['nextPageToken'],
      moderationStatus='published'
    ).execute()
  else:
    # notify that no more pages are left
    print('No more comment pages left.')
    break

51 comments in list
Next comment page found. Now extracting data.

102 comments in list
Next comment page found. Now extracting data.

124 comments in list
No more comment pages left.

In [ ]:
youtube_corpus = pd.DataFrame(
  comments, columns=['title', 'link', 'date_published', 'text', 'like_count', 'reply_parent_id'])
youtube_corpus

,title,link,date_published,text,like_count,reply_parent_id
0,Escape of guo is a reflection of country&#39;s...,https://www.youtube.com/watch?v=0v1XHgWyIvU&lc...,2024-08-27T10:40:10Z,Escape of guo is a reflection of country's st...,0,NaN
1,BAKIT masama bang magsinungaling ? Sino bang t...,https://www.youtube.com/watch?v=0v1XHgWyIvU&lc...,2024-08-26T02:25:48Z,BAKIT masama bang magsinungaling ? Sino bang t...,0,NaN
2,Ano ka ngayon Honti Virus Nga Nga ?,https://www.youtube.com/watch?v=0v1XHgWyIvU&lc...,2024-08-26T02:19:50Z,Ano ka ngayon Honti Virus Nga Nga ?,0,NaN
3,"Grabe nakalagpas sa immigration, ano yan hindi...",https://www.youtube.com/watch?v=0v1XHgWyIvU&lc...,2024-08-22T07:58:58Z,"Grabe nakalagpas sa immigration, ano yan hindi...",0,NaN
4,naku duterte bat mo nman pinatakas yung alaga mo,https://www.youtube.com/watch?v=0v1XHgWyIvU&lc...,2024-08-22T07:05:19Z,naku duterte bat mo nman pinatakas yung alaga mo,0,NaN
...,...,...,...,...,...,...
119,Magkano kaya binayad oara maka eskapo?,https://www.youtube.com/watch?v=0v1XHgWyIvU&lc...,2024-08-20T11:02:17Z,Magkano kaya binayad oara maka eskapo?,0,UgzidE_cOM1z3f7pnCF4AaABAg
120,Nagtatago lang yan,https://www.youtube.com/watch?v=0v1XHgWyIvU&lc...,2024-08-19T12:15:42Z,Nagtatago lang yan,1,NaN
121,Iba talaga pag may Pera. Lahat ma bibili. Hay ...,https://www.youtube.com/watch?v=0v1XHgWyIvU&lc...,2024-08-19T12:14:12Z,Iba talaga pag may Pera. Lahat ma bibili. Hay ...,8,NaN
122,Bakit nakalabas,https://www.youtube.com/watch?v=0v1XHgWyIvU&lc...,2024-08-19T12:12:46Z,Bakit nakalabas,2,NaN
123,Pilipinos are FOR SALE !!<br>Alam mo yan,https://www.youtube.com/watch?v=0v1XHgWyIvU&lc...,2024-08-19T12:44:08Z,Pilipinos are FOR SALE !!\nAlam mo yan,0,UgzWDcMGlQwTh6ULlKJ4AaABAg

## Function `extract_youtube_comments`

Now, we can define a function that extracts a certain number of comments for a particular video and returns a list of these comments.

In [ ]:
def extract_youtube_comments(video_id, no_comments):
  """
  Extracts comments from a YouTube video.

  Args:
    video_id (str): The ID of the YouTube video.
    no_comments (int): The number of comments to extract.

  Returns:
    pandas.DataFrame: A DataFrame containing the extracted comments with the following columns:
      - title (str): The display text of the comment.
      - link (str): The URL of the comment.
      - date_published (str): The date and time when the comment was published.
      - text (str): The original text of the comment.
      - like_count (int): The number of likes the comment has received.
      - reply_parent_id (float): The ID of the parent comment if the comment is a reply, otherwise NaN.
  """
  # re-initialize list of YouTube comments
  comments = []

  # get first page of the comments
  video_response = youtube.commentThreads().list(
    videoId=video_id, part='snippet,replies', maxResults=50,
    order='time', moderationStatus='published'
  ).execute()

  while len(comments) < no_comments:
    # iterate through items
    for item in video_response['items']:
      ##### Parent Comments #####
      # extract comment from each item
      comment = item['snippet']['topLevelComment']['snippet']

      # append comment to list of comments
      comments.append([
        comment['textDisplay'],
        f'https://www.youtube.com/watch?v={video_id}&lc={item["snippet"]["topLevelComment"]["id"]}',
        comment['publishedAt'],
        comment['textOriginal'],
        comment['likeCount'],
        np.nan
      ])

      ##### Reply Comments #####
      # count number of replies
      total_reply_count = item['snippet']['totalReplyCount']

      # if there is at least one reply
      if total_reply_count > 0:
        parent_id = item["snippet"]["topLevelComment"]["id"]

        replies = youtube.comments().list(
          part='snippet',
          parentId=parent_id
        ).execute()

        # iterate through the replies
        for reply in replies['items']:
          # extract text from each reply
          # append reply to list of comments
          replyBody = reply['snippet']
          comments.append([
            replyBody['textDisplay'],
            f"https://www.youtube.com/watch?v={video_id}&lc={reply['id']}",
            replyBody['publishedAt'],
            replyBody['textOriginal'],
            replyBody['likeCount'],
            replyBody['parentId']
          ])

    ##### Next Page #####
    # print number of comments
    print(str(len(comments)) + ' comments in list')

    # if there is a next page to the comment result
    if 'nextPageToken' in video_response:
      # notify that next page has been found
      print('Next comment page found. Now extracting data. \n')

      # get the next page
      video_response = youtube.commentThreads().list(
        videoId=video_id, part='snippet,replies', maxResults=50,
        order='time', pageToken=video_response['nextPageToken'],
        moderationStatus='published'
      ).execute()
    else:
      # notify that no more pages are left
      print('No more comment pages left.\n')
      break

  return pd.DataFrame(
    comments, columns=['title', 'link', 'date_published', 'text', 'like_count', 'reply_parent_id']
  )

In [ ]:
# Get video IDs from links
video_ids = []

with open("video_links.txt", "r", encoding="utf-8") as f:
    for line in f:
        url = line.strip()
        if "watch?v=" in url:
            video_id = url.split("watch?v=")[-1].split("&")[0]  # handle extra params
            video_ids.append(video_id)

print(video_ids)

['1GbouN7n5lQ', 'djoqnf0wAHc', 'M9VNL9Wmugs', 'DirGZd18TrU', 'aKjVN7e7aP8', 'Ew3Fp-iATtk', 'lnFpkeOVuOU', 'CtSFQJ7s8JQ', 'N3_2m8d51Pk', 'DET2AUmRmng', 'ghUKUsAnWUs', 'PcKpeRQT76I', 'uR8eELghGaU', 'MJ6zICsj2lM', 'IpoKMx9mquw', 'QA9MqXShkx4', '9or0sXYbfe8', 'Y7xz8PhrQU0', 'INiVHrkKwYo', '2QYpNI5WVZQ', 'PEBN_UMUil0', 'C6we9f-4NPA', 'joacZ2YWjTs']

In [ ]:
wphsea_youtube_corpus = None

for video_id in video_ids:
  print(f'Extracting comments from video: {video_id}')
  if wphsea_youtube_corpus is None:
    wphsea_youtube_corpus = extract_youtube_comments(video_id, 750)
  else:
    wphsea_youtube_corpus = pd.concat([
      wphsea_youtube_corpus, extract_youtube_comments(video_id, 750)
    ])

wphsea_youtube_corpus

Extracting comments from video: 1GbouN7n5lQ
40 comments in list
No more comment pages left.

Extracting comments from video: djoqnf0wAHc
51 comments in list
Next comment page found. Now extracting data.

101 comments in list
Next comment page found. Now extracting data.

152 comments in list
Next comment page found. Now extracting data.

203 comments in list
Next comment page found. Now extracting data.

254 comments in list
Next comment page found. Now extracting data.

304 comments in list
Next comment page found. Now extracting data.

357 comments in list
Next comment page found. Now extracting data.

416 comments in list
Next comment page found. Now extracting data.

472 comments in list
Next comment page found. Now extracting data.

525 comments in list
Next comment page found. Now extracting data.

577 comments in list
Next comment page found. Now extracting data.

630 comments in list
Next comment page found. Now extracting data.

696 comments in list
Next comment page found. Now extracting data.

697 comments in list
No more comment pages left.

Extracting comments from video: M9VNL9Wmugs
50 comments in list
Next comment page found. Now extracting data.

100 comments in list
Next comment page found. Now extracting data.

150 comments in list
Next comment page found. Now extracting data.

200 comments in list
Next comment page found. Now extracting data.

250 comments in list
Next comment page found. Now extracting data.

311 comments in list
Next comment page found. Now extracting data.

416 comments in list
Next comment page found. Now extracting data.

468 comments in list
No more comment pages left.

Extracting comments from video: DirGZd18TrU
55 comments in list
Next comment page found. Now extracting data.

76 comments in list
No more comment pages left.

Extracting comments from video: aKjVN7e7aP8
65 comments in list
Next comment page found. Now extracting data.

69 comments in list
No more comment pages left.

Extracting comments from video: Ew3Fp-iATtk
50 comments in list
Next comment page found. Now extracting data.

100 comments in list
Next comment page found. Now extracting data.

150 comments in list
Next comment page found. Now extracting data.

200 comments in list
Next comment page found. Now extracting data.

251 comments in list
Next comment page found. Now extracting data.

301 comments in list
Next comment page found. Now extracting data.

354 comments in list
Next comment page found. Now extracting data.

404 comments in list
Next comment page found. Now extracting data.

455 comments in list
Next comment page found. Now extracting data.

507 comments in list
Next comment page found. Now extracting data.

557 comments in list
Next comment page found. Now extracting data.

626 comments in list
Next comment page found. Now extracting data.

684 comments in list
Next comment page found. Now extracting data.

756 comments in list
Next comment page found. Now extracting data.

Extracting comments from video: lnFpkeOVuOU
51 comments in list
Next comment page found. Now extracting data.

101 comments in list
Next comment page found. Now extracting data.

153 comments in list
Next comment page found. Now extracting data.

229 comments in list
Next comment page found. Now extracting data.

233 comments in list
No more comment pages left.

Extracting comments from video: CtSFQJ7s8JQ
51 comments in list
Next comment page found. Now extracting data.

102 comments in list
Next comment page found. Now extracting data.

152 comments in list
Next comment page found. Now extracting data.

202 comments in list
Next comment page found. Now extracting data.

260 comments in list
Next comment page found. Now extracting data.

310 comments in list
Next comment page found. Now extracting data.

360 comments in list
Next comment page found. Now extracting data.

410 comments in list
Next comment page found. Now extracting data.

460 comments in list
Next comment page found. Now extracting data.

510 comments in list
Next comment page found. Now extracting data.

560 comments in list
Next comment page found. Now extracting data.

610 comments in list
Next comment page found. Now extracting data.

660 comments in list
Next comment page found. Now extracting data.

711 comments in list
Next comment page found. Now extracting data.

761 comments in list
Next comment page found. Now extracting data.

Extracting comments from video: N3_2m8d51Pk
50 comments in list
Next comment page found. Now extracting data.

100 comments in list
Next comment page found. Now extracting data.

152 comments in list
Next comment page found. Now extracting data.

204 comments in list
Next comment page found. Now extracting data.

254 comments in list
Next comment page found. Now extracting data.

304 comments in list
Next comment page found. Now extracting data.

355 comments in list
Next comment page found. Now extracting data.

405 comments in list
Next comment page found. Now extracting data.

455 comments in list
Next comment page found. Now extracting data.

505 comments in list
Next comment page found. Now extracting data.

556 comments in list
Next comment page found. Now extracting data.

606 comments in list
Next comment page found. Now extracting data.

656 comments in list
Next comment page found. Now extracting data.

706 comments in list
Next comment page found. Now extracting data.

756 comments in list
Next comment page found. Now extracting data.

Extracting comments from video: DET2AUmRmng
50 comments in list
Next comment page found. Now extracting data.

100 comments in list
Next comment page found. Now extracting data.

150 comments in list
Next comment page found. Now extracting data.

200 comments in list
Next comment page found. Now extracting data.

250 comments in list
Next comment page found. Now extracting data.

300 comments in list
Next comment page found. Now extracting data.

350 comments in list
Next comment page found. Now extracting data.

400 comments in list
Next comment page found. Now extracting data.

450 comments in list
Next comment page found. Now extracting data.

500 comments in list
Next comment page found. Now extracting data.

550 comments in list
Next comment page found. Now extracting data.

601 comments in list
Next comment page found. Now extracting data.

651 comments in list
Next comment page found. Now extracting data.

706 comments in list
Next comment page found. Now extracting data.

757 comments in list
Next comment page found. Now extracting data.

Extracting comments from video: ghUKUsAnWUs
50 comments in list
Next comment page found. Now extracting data.

100 comments in list
Next comment page found. Now extracting data.

150 comments in list
Next comment page found. Now extracting data.

200 comments in list
Next comment page found. Now extracting data.

250 comments in list
Next comment page found. Now extracting data.

300 comments in list
Next comment page found. Now extracting data.

350 comments in list
Next comment page found. Now extracting data.

401 comments in list
Next comment page found. Now extracting data.

451 comments in list
Next comment page found. Now extracting data.

502 comments in list
Next comment page found. Now extracting data.

561 comments in list
Next comment page found. Now extracting data.

611 comments in list
Next comment page found. Now extracting data.

671 comments in list
Next comment page found. Now extracting data.

721 comments in list
Next comment page found. Now extracting data.

771 comments in list
Next comment page found. Now extracting data.

Extracting comments from video: PcKpeRQT76I
50 comments in list
Next comment page found. Now extracting data.

100 comments in list
Next comment page found. Now extracting data.

150 comments in list
Next comment page found. Now extracting data.

200 comments in list
Next comment page found. Now extracting data.

250 comments in list
Next comment page found. Now extracting data.

300 comments in list
Next comment page found. Now extracting data.

350 comments in list
Next comment page found. Now extracting data.

400 comments in list
Next comment page found. Now extracting data.

450 comments in list
Next comment page found. Now extracting data.

501 comments in list
Next comment page found. Now extracting data.

551 comments in list
Next comment page found. Now extracting data.

602 comments in list
Next comment page found. Now extracting data.

652 comments in list
Next comment page found. Now extracting data.

703 comments in list
Next comment page found. Now extracting data.

753 comments in list
Next comment page found. Now extracting data.

Extracting comments from video: uR8eELghGaU
51 comments in list
Next comment page found. Now extracting data.

101 comments in list
Next comment page found. Now extracting data.

151 comments in list
Next comment page found. Now extracting data.

202 comments in list
Next comment page found. Now extracting data.

253 comments in list
Next comment page found. Now extracting data.

303 comments in list
Next comment page found. Now extracting data.

354 comments in list
Next comment page found. Now extracting data.

406 comments in list
Next comment page found. Now extracting data.

456 comments in list
Next comment page found. Now extracting data.

507 comments in list
Next comment page found. Now extracting data.

557 comments in list
Next comment page found. Now extracting data.

616 comments in list
Next comment page found. Now extracting data.

667 comments in list
Next comment page found. Now extracting data.

718 comments in list
Next comment page found. Now extracting data.

788 comments in list
Next comment page found. Now extracting data.

Extracting comments from video: MJ6zICsj2lM
50 comments in list
Next comment page found. Now extracting data.

100 comments in list
Next comment page found. Now extracting data.

151 comments in list
Next comment page found. Now extracting data.

202 comments in list
Next comment page found. Now extracting data.

252 comments in list
Next comment page found. Now extracting data.

303 comments in list
Next comment page found. Now extracting data.

353 comments in list
Next comment page found. Now extracting data.

404 comments in list
Next comment page found. Now extracting data.

458 comments in list
Next comment page found. Now extracting data.

510 comments in list
Next comment page found. Now extracting data.

561 comments in list
Next comment page found. Now extracting data.

640 comments in list
Next comment page found. Now extracting data.

690 comments in list
Next comment page found. Now extracting data.

752 comments in list
Next comment page found. Now extracting data.

Extracting comments from video: IpoKMx9mquw
52 comments in list
Next comment page found. Now extracting data.

102 comments in list
Next comment page found. Now extracting data.

152 comments in list
Next comment page found. Now extracting data.

202 comments in list
Next comment page found. Now extracting data.

256 comments in list
Next comment page found. Now extracting data.

310 comments in list
Next comment page found. Now extracting data.

361 comments in list
Next comment page found. Now extracting data.

417 comments in list
Next comment page found. Now extracting data.

468 comments in list
Next comment page found. Now extracting data.

520 comments in list
Next comment page found. Now extracting data.

571 comments in list
Next comment page found. Now extracting data.

621 comments in list
Next comment page found. Now extracting data.

676 comments in list
Next comment page found. Now extracting data.

737 comments in list
Next comment page found. Now extracting data.

796 comments in list
Next comment page found. Now extracting data.

Extracting comments from video: QA9MqXShkx4
50 comments in list
Next comment page found. Now extracting data.

100 comments in list
Next comment page found. Now extracting data.

150 comments in list
Next comment page found. Now extracting data.

201 comments in list
Next comment page found. Now extracting data.

HttpError: <HttpError 400 when requesting https://youtube.googleapis.com/youtube/v3/commentThreads?videoId=QA9MqXShkx4&part=snippet%2Creplies&maxResults=50&order=time&pageToken=Z2V0X25ld2VzdF9maXJzdC0tQ2dnSWdBUVZGN2ZST0JJRkNLZ2dHQUFTQlFpZElCZ0JFZ1VJaUNBWUFCSUZDSWNnR0FBU0JRaUpJQmdBSWc0S0RBand5OF9GQmhEUXFjUEZBUQ%3D%3D&moderationStatus=published&key=AIzaSyDNAvtKMzRxwcpG0dKkubOrdzL1eydppJ0&alt=json returned "The API server failed to successfully process the request. While this can be a transient error, it usually indicates that the request's input is invalid. Check the structure of the <code>commentThread</code> resource in the request body to ensure that it is valid.". Details: "[{'message': "The API server failed to successfully process the request. While this can be a transient error, it usually indicates that the request's input is invalid. Check the structure of the <code>commentThread</code> resource in the request body to ensure that it is valid.", 'domain': 'youtube.commentThread', 'reason': 'processingFailure', 'location': 'body', 'locationType': 'other'}]">

In [ ]:
wphsea_youtube_corpus

,title,link,date_published,text,like_count,reply_parent_id
0,Invite niyo si magalong at Zaldy Co bat ba aya...,https://www.youtube.com/watch?v=1GbouN7n5lQ&lc...,2025-09-03T06:07:34Z,Invite niyo si magalong at Zaldy Co bat ba aya...,0,NaN
1,Invite niyo si Zaldy Co,https://www.youtube.com/watch?v=1GbouN7n5lQ&lc...,2025-09-03T06:05:30Z,Invite niyo si Zaldy Co,0,NaN
2,Kung sino ung important at substantial yung si...,https://www.youtube.com/watch?v=1GbouN7n5lQ&lc...,2025-09-03T04:32:06Z,Kung sino ung important at substantial yung si...,0,NaN
3,Muro muro talaga ang hearing na ito dapat laha...,https://www.youtube.com/watch?v=1GbouN7n5lQ&lc...,2025-09-03T02:25:18Z,Muro muro talaga ang hearing na ito dapat laha...,0,NaN
4,I don’t know why they don’t have lie detectors...,https://www.youtube.com/watch?v=1GbouN7n5lQ&lc...,2025-09-03T02:00:20Z,I don’t know why they don’t have lie detectors...,0,NaN
...,...,...,...,...,...,...
791,Res145: Conduct a JOINT Inquiry in Aid of Legi...,https://www.youtube.com/watch?v=IpoKMx9mquw&lc...,2025-08-21T05:48:25Z,Res145: Conduct a JOINT Inquiry in Aid of Legi...,0,NaN
792,So ano ka ngayon ADIONG TAKOT BA MA EXPOSE ANG...,https://www.youtube.com/watch?v=IpoKMx9mquw&lc...,2025-08-21T05:42:34Z,So ano ka ngayon ADIONG TAKOT BA MA EXPOSE ANG...,0,NaN
793,Hahaha balita pa sa mga BUWAYANG TROPA<br>papa...,https://www.youtube.com/watch?v=IpoKMx9mquw&lc...,2025-08-21T05:38:10Z,Hahaha balita pa sa mga BUWAYANG TROPA\npapang...,0,NaN
794,"Tama si Cong De Lima, Lalabas na Moro -moro la...",https://www.youtube.com/watch?v=IpoKMx9mquw&lc...,2025-08-21T05:36:52Z,"Tama si Cong De Lima, Lalabas na Moro -moro la...",0,NaN
795,I liked her/Congress woman Laila de lima,https://www.youtube.com/watch?v=IpoKMx9mquw&lc...,2025-08-21T05:36:08Z,I liked her/Congress woman Laila de lima,0,NaN

We can now save these comments to a dataframe and Excel file.

In [ ]:
import openpyxl

file_name = 'youtube_corpus.xlsx'

wphsea_youtube_corpus.to_excel(file_name)
print(f'File saved to {file_name}')

File saved to youtube_corpus.xlsx

What we've done so far is extract comments for **one** video. If you want to extract comments for multiple videos, you'll have to use the `channel`, `search`, or `playlist` resource objects of the YouTube API. You can study these more through the documentation.

However, note that each account has an allocation of 10,000 units per day. Each call that uses the API costs a certain number of units, and if you reach 10,000, you won't be able to properly use the API (and possibly YouTube) until the next day.

Other APIs you might be interested in exploring:
*   Genius API for extracting song lyrics (https://docs.genius.com/)
*   Python Reddit API Wrapper (PRAW) for extracting Reddit posts (https://praw.readthedocs.io/en/stable/)
*   Tweepy for extracting tweets (but Elon kinda ruined it now) (https://www.tweepy.org/)

# Method 3: Facepager

Facepager is an application made for automating data extraction (esp. for Facebook). Follow the installation instructions in this page: https://github.com/strohne/Facepager

To learn more about how to use Facepager, navigate through its wiki page: https://github.com/strohne/Facepager/wiki/Getting-Started